-- =========================
-- Mound Hounds Pick'em: Consolidated Supabase Schema
-- =========================

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

-- Profiles (extends auth.users)
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  team_name text not null unique,
  phone_number text,
  phone_carrier text,
  role text not null default 'participant' check (role in ('admin', 'participant')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

-- Drivers
create table if not exists public.drivers (
  id bigint generated by default as identity primary key,
  driver_name text not null unique,
  image_url text,
  championship_points integer not null default 0 check (championship_points >= 0),
  current_standing integer not null check (current_standing > 0),
  group_number smallint not null check (group_number between 1 and 6),
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

-- Races
create table if not exists public.races (
  id bigint generated by default as identity primary key,
  race_name text not null,
  pick_format text not null default 'standard' check (pick_format in ('standard', 'indy_500')),
  title_image_url text,
  qualifying_start_at timestamptz not null,
  race_date timestamptz not null,
  payout numeric(10,2) not null default 0,
  official_winning_average_speed numeric(8,3) check (official_winning_average_speed >= 0),
  results_status text not null default 'draft' check (results_status in ('draft', 'published')),
  results_published_at timestamptz,
  winner_profile_id uuid references public.profiles(id) on delete set null,
  winner_source text not null default 'auto' check (winner_source in ('auto', 'manual')),
  winner_is_manual_override boolean not null default false,
  winner_auto_eligible_at timestamptz,
  winner_set_at timestamptz,
  is_archived boolean not null default false,
  archived_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (race_name, race_date),
  check (qualifying_start_at <= race_date)
);

-- Picks (exactly 1 driver per group + tiebreaker speed)
create table if not exists public.picks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  race_id bigint not null references public.races(id) on delete cascade,
  average_speed numeric(7,3) not null check (average_speed > 0),
  driver_group1_id bigint not null references public.drivers(id),
  driver_group2_id bigint not null references public.drivers(id),
  driver_group3_id bigint not null references public.drivers(id),
  driver_group4_id bigint not null references public.drivers(id),
  driver_group5_id bigint not null references public.drivers(id),
  driver_group6_id bigint not null references public.drivers(id),
  driver_group7_id bigint references public.drivers(id),
  driver_group8_id bigint references public.drivers(id),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (user_id, race_id)
);

-- Results (official points by race/driver)
create table if not exists public.results (
  id bigint generated by default as identity primary key,
  race_id bigint not null references public.races(id) on delete cascade,
  driver_id bigint not null references public.drivers(id) on delete cascade,
  points integer not null check (points >= 0),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (race_id, driver_id)
);

-- Race-specific driver group snapshots (freeze group mapping at results publication time)
create table if not exists public.race_driver_groups (
  race_id bigint not null references public.races(id) on delete cascade,
  driver_id bigint not null references public.drivers(id) on delete cascade,
  group_number smallint not null check (group_number between 1 and 8),
  qualifying_position integer check (qualifying_position is null or qualifying_position > 0),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (race_id, driver_id)
);

-- Feedback submissions
create table if not exists public.feedback_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  feedback_type text not null check (feedback_type in ('bug', 'improvement')),
  category text not null,
  context_page text,
  details text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

-- Pick reminder notifications (cron dedupe/log)
create table if not exists public.pick_reminders (
  id bigint generated by default as identity primary key,
  race_id bigint not null references public.races(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  reminder_type text not null check (reminder_type in ('4d', '2d', '2h')),
  channel text not null check (channel in ('email', 'sms')),
  recipient text not null,
  delivery_status text not null default 'pending' check (delivery_status in ('pending', 'sent')),
  delivery_id text,
  sent_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (race_id, user_id, reminder_type, channel)
);

-- Indexes
create index if not exists idx_drivers_group on public.drivers(group_number, current_standing);
create index if not exists idx_drivers_points on public.drivers(championship_points desc, current_standing asc);
create index if not exists idx_races_date on public.races(race_date);
create index if not exists idx_races_qualifying_start on public.races(qualifying_start_at);
create index if not exists idx_races_winner_auto_eligible on public.races(winner_auto_eligible_at);
create index if not exists idx_races_is_archived on public.races(is_archived, race_date);
create index if not exists idx_races_results_status_date on public.races(results_status, race_date);
create index if not exists idx_picks_race on public.picks(race_id);
create index if not exists idx_picks_user on public.picks(user_id);
create index if not exists idx_results_race on public.results(race_id);
create index if not exists idx_race_driver_groups_race_group on public.race_driver_groups(race_id, group_number);
create index if not exists idx_race_driver_groups_race_qualifying_position
on public.race_driver_groups(race_id, qualifying_position)
where qualifying_position is not null;
create index if not exists idx_feedback_items_created_at on public.feedback_items(created_at desc);
create index if not exists idx_feedback_items_user on public.feedback_items(user_id);
create index if not exists idx_pick_reminders_race on public.pick_reminders(race_id, reminder_type, channel);
create index if not exists idx_pick_reminders_user on public.pick_reminders(user_id, created_at desc);

-- updated_at triggers
drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists trg_drivers_updated_at on public.drivers;
create trigger trg_drivers_updated_at
before update on public.drivers
for each row execute function public.set_updated_at();

drop trigger if exists trg_races_updated_at on public.races;
create trigger trg_races_updated_at
before update on public.races
for each row execute function public.set_updated_at();

drop trigger if exists trg_picks_updated_at on public.picks;
create trigger trg_picks_updated_at
before update on public.picks
for each row execute function public.set_updated_at();

drop trigger if exists trg_results_updated_at on public.results;
create trigger trg_results_updated_at
before update on public.results
for each row execute function public.set_updated_at();

create or replace function public.ensure_race_driver_groups_snapshot_from_results()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  race_pick_format text;
begin
  select r.pick_format
    into race_pick_format
  from public.races r
  where r.id = new.race_id;

  if race_pick_format is null then
    raise exception 'Race not found for result group snapshot.';
  end if;

  if race_pick_format = 'indy_500' then
    if not exists (
      select 1
      from public.race_driver_groups rg
      where rg.race_id = new.race_id
      limit 1
    ) then
      raise exception 'Indianapolis 500 qualifying order must be uploaded before saving race results.';
    end if;

    return new;
  end if;

  if not exists (
    select 1
    from public.race_driver_groups rg
    where rg.race_id = new.race_id
    limit 1
  ) then
    insert into public.race_driver_groups (race_id, driver_id, group_number)
    select
      new.race_id,
      d.id,
      d.group_number
    from public.drivers d
    where d.is_active = true
      and d.group_number between 1 and 6
    on conflict (race_id, driver_id) do nothing;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_results_ensure_race_driver_group_snapshot on public.results;
create trigger trg_results_ensure_race_driver_group_snapshot
before insert or update of race_id on public.results
for each row execute function public.ensure_race_driver_groups_snapshot_from_results();

drop trigger if exists trg_race_driver_groups_updated_at on public.race_driver_groups;
create trigger trg_race_driver_groups_updated_at
before update on public.race_driver_groups
for each row execute function public.set_updated_at();

drop trigger if exists trg_feedback_items_updated_at on public.feedback_items;
create trigger trg_feedback_items_updated_at
before update on public.feedback_items
for each row execute function public.set_updated_at();

drop trigger if exists trg_pick_reminders_updated_at on public.pick_reminders;
create trigger trg_pick_reminders_updated_at
before update on public.pick_reminders
for each row execute function public.set_updated_at();

-- Enforce pick lock at the database layer
create or replace function public.enforce_pick_deadline()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  previous_race_name text;
  previous_results_status text;
  race_qualifying_start_at timestamptz;
  race_start_at timestamptz;
  race_is_archived boolean;
  race_pick_format text;
  pick_lock_at timestamptz;
begin
  select r.qualifying_start_at, r.race_date, r.is_archived, r.pick_format
    into race_qualifying_start_at, race_start_at, race_is_archived, race_pick_format
  from public.races r
  where r.id = new.race_id;

  if race_qualifying_start_at is null or race_start_at is null then
    raise exception 'Race not found for pick submission';
  end if;

  if race_is_archived then
    raise exception 'Picks are disabled for archived races.';
  end if;

  select previous_race.race_name, previous_race.results_status
    into previous_race_name, previous_results_status
  from public.races previous_race
  where previous_race.is_archived = false
    and previous_race.race_date < race_start_at
    and extract(year from previous_race.race_date at time zone 'America/Indiana/Indianapolis') =
      extract(year from race_start_at at time zone 'America/Indiana/Indianapolis')
  order by previous_race.race_date desc
  limit 1;

  if previous_race_name is not null and previous_results_status <> 'published' then
    raise exception 'Picks are unavailable until % results are published.', previous_race_name;
  end if;

  pick_lock_at := case
    when race_pick_format = 'indy_500' then race_start_at
    else race_qualifying_start_at
  end;

  if pick_lock_at <= now() then
    if race_pick_format = 'indy_500' then
      raise exception 'Picks are locked because the race has already started.';
    end if;

    raise exception 'Picks are locked because qualifying has already started.';
  end if;

  return new;
end;
$$;

drop trigger if exists trg_enforce_pick_deadline on public.picks;
create trigger trg_enforce_pick_deadline
before insert or update on public.picks
for each row execute function public.enforce_pick_deadline();

-- Validate pick groups + uniqueness of selected drivers
create or replace function public.validate_pick_groups()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  selected_driver_ids bigint[];
  distinct_count integer;
  group_index integer;
  selected_driver_id bigint;
  race_pick_format text;
  expected_group_count integer;
begin
  select r.pick_format
    into race_pick_format
  from public.races r
  where r.id = new.race_id;

  if race_pick_format is null then
    raise exception 'Race not found for pick validation';
  end if;

  if race_pick_format = 'indy_500' then
    expected_group_count := 8;
    selected_driver_ids := array[
      new.driver_group1_id,
      new.driver_group2_id,
      new.driver_group3_id,
      new.driver_group4_id,
      new.driver_group5_id,
      new.driver_group6_id,
      new.driver_group7_id,
      new.driver_group8_id
    ];

    if new.driver_group7_id is null or new.driver_group8_id is null then
      raise exception 'Indianapolis 500 picks require one driver from each of 8 groups';
    end if;

    for group_index in 1..8 loop
      selected_driver_id := selected_driver_ids[group_index];

      if not exists (
        select 1
        from public.drivers d
        join public.race_driver_groups rg
          on rg.driver_id = d.id
        where d.id = selected_driver_id
          and d.is_active
          and rg.race_id = new.race_id
          and rg.group_number = group_index
      ) then
        raise exception 'Invalid Group % driver for Indianapolis 500 qualifying order', group_index;
      end if;
    end loop;
  else
    expected_group_count := 6;
    selected_driver_ids := array[
      new.driver_group1_id,
      new.driver_group2_id,
      new.driver_group3_id,
      new.driver_group4_id,
      new.driver_group5_id,
      new.driver_group6_id
    ];

    if new.driver_group7_id is not null or new.driver_group8_id is not null then
      raise exception 'Standard race picks must contain exactly 6 drivers';
    end if;

    for group_index in 1..6 loop
      selected_driver_id := selected_driver_ids[group_index];

      if not exists (
        select 1
        from public.drivers d
        where d.id = selected_driver_id
          and d.group_number = group_index
          and d.is_active
      ) then
        raise exception 'Invalid Group % driver', group_index;
      end if;
    end loop;
  end if;

  select count(distinct d) into distinct_count
  from unnest(selected_driver_ids) as t(d);

  if distinct_count <> expected_group_count then
    raise exception 'Each pick must contain % distinct drivers', expected_group_count;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_validate_pick_groups on public.picks;
create trigger trg_validate_pick_groups
before insert or update on public.picks
for each row execute function public.validate_pick_groups();

-- Auto-create profile when auth user is created
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, team_name)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', ''),
    coalesce(nullif(new.raw_user_meta_data->>'team_name', ''), 'Team-' || new.id::text)
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- Admin helper for policies
create or replace function public.is_admin(uid uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = uid
      and p.role = 'admin'
  );
$$;

grant execute on function public.is_admin(uuid) to authenticated;

-- Participants may edit profile details, but only admins may assign or change roles.
create or replace function public.protect_profile_role()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.role() = 'authenticated' and not public.is_admin(auth.uid()) then
    if tg_op = 'INSERT' and new.role <> 'participant' then
      raise exception 'Only an administrator may assign profile roles.';
    end if;

    if tg_op = 'UPDATE' and new.role is distinct from old.role then
      raise exception 'Only an administrator may change profile roles.';
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_protect_profile_role on public.profiles;
create trigger trg_protect_profile_role
before insert or update of role on public.profiles
for each row execute function public.protect_profile_role();

revoke all on function public.protect_profile_role() from public;

-- Snapshot the exact field that must be present before results can be published.
create or replace function public.ensure_race_result_field_snapshot(p_race_id bigint)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  existing_result_count integer;
  race_is_archived boolean;
  race_pick_format text;
  race_results_status text;
  snapshot_count integer;
begin
  select r.is_archived, r.pick_format, r.results_status
    into race_is_archived, race_pick_format, race_results_status
  from public.races r
  where r.id = p_race_id
  for update;

  if race_pick_format is null then
    raise exception 'Selected race was not found.';
  end if;

  if race_is_archived then
    raise exception 'Selected race is archived. Unarchive it before updating results.';
  end if;

  select count(*) into snapshot_count
  from public.race_driver_groups rg
  where rg.race_id = p_race_id;

  select count(*) into existing_result_count
  from public.results result_row
  where result_row.race_id = p_race_id;

  if snapshot_count = 0 then
    if existing_result_count > 0 and race_results_status = 'published' then
      raise exception 'This legacy published race has no historical driver-group snapshot. Current groups cannot be used to reconstruct it safely.';
    end if;

    if race_pick_format = 'indy_500' then
      raise exception 'Indianapolis 500 qualifying order must be uploaded before saving results.';
    end if;

    insert into public.race_driver_groups (race_id, driver_id, group_number)
    select p_race_id, d.id, d.group_number
    from public.drivers d
    where d.is_active = true
      and d.group_number between 1 and 6
    on conflict (race_id, driver_id) do nothing;

    select count(*) into snapshot_count
    from public.race_driver_groups rg
    where rg.race_id = p_race_id;
  end if;

  if snapshot_count = 0 then
    raise exception 'No drivers are available in the race result field.';
  end if;

  return snapshot_count;
end;
$$;

revoke all on function public.ensure_race_result_field_snapshot(bigint) from public, anon, authenticated;

create or replace function public.refresh_driver_standings_from_published_results()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  active_driver_count integer;
begin
  if coalesce(auth.role(), '') <> 'service_role' and not public.is_admin(auth.uid()) then
    raise exception 'Admin access required.';
  end if;

  update public.drivers d
  set championship_points = coalesce(points_by_driver.total_points, 0)
  from (
    select
      driver.id as driver_id,
      coalesce(sum(result_row.points) filter (where race.results_status = 'published'), 0)::integer as total_points
    from public.drivers driver
    left join public.results result_row on result_row.driver_id = driver.id
    left join public.races race on race.id = result_row.race_id
    group by driver.id
  ) points_by_driver
  where d.id = points_by_driver.driver_id;

  with ranked_active as (
    select
      d.id,
      row_number() over (
        order by d.championship_points desc, d.current_standing asc, d.driver_name asc
      )::integer as next_standing
    from public.drivers d
    where d.is_active = true
  )
  update public.drivers d
  set
    current_standing = ranked_active.next_standing,
    group_number = case
      when ranked_active.next_standing <= 4 then 1
      when ranked_active.next_standing <= 8 then 2
      when ranked_active.next_standing <= 12 then 3
      when ranked_active.next_standing <= 16 then 4
      when ranked_active.next_standing <= 20 then 5
      else 6
    end
  from ranked_active
  where d.id = ranked_active.id;

  select count(*) into active_driver_count
  from public.drivers d
  where d.is_active = true;

  with ranked_inactive as (
    select
      d.id,
      (active_driver_count + row_number() over (
        order by d.current_standing asc, d.driver_name asc
      ))::integer as next_standing
    from public.drivers d
    where d.is_active = false
  )
  update public.drivers d
  set
    current_standing = ranked_inactive.next_standing,
    group_number = 6
  from ranked_inactive
  where d.id = ranked_inactive.id;
end;
$$;

revoke all on function public.refresh_driver_standings_from_published_results() from public, anon;
grant execute on function public.refresh_driver_standings_from_published_results() to authenticated, service_role;

create or replace function public.save_race_result_draft(
  p_race_id bigint,
  p_driver_id bigint,
  p_points integer
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin(auth.uid()) then
    raise exception 'Admin access required.';
  end if;

  if p_points is null or p_points < 0 then
    raise exception 'Points must be a non-negative integer.';
  end if;

  perform public.ensure_race_result_field_snapshot(p_race_id);

  if not exists (
    select 1
    from public.race_driver_groups rg
    where rg.race_id = p_race_id
      and rg.driver_id = p_driver_id
  ) then
    raise exception 'Selected driver is not part of this race result field.';
  end if;

  insert into public.results (race_id, driver_id, points)
  values (p_race_id, p_driver_id, p_points)
  on conflict (race_id, driver_id)
  do update set points = excluded.points;

  update public.races
  set
    results_status = 'draft',
    results_published_at = null,
    winner_profile_id = null,
    winner_source = 'auto',
    winner_is_manual_override = false,
    winner_auto_eligible_at = null,
    winner_set_at = null
  where id = p_race_id;

  perform public.refresh_driver_standings_from_published_results();
end;
$$;

revoke all on function public.save_race_result_draft(bigint, bigint, integer) from public, anon;
grant execute on function public.save_race_result_draft(bigint, bigint, integer) to authenticated;

create or replace function public.publish_saved_race_results(
  p_race_id bigint,
  p_official_winning_average_speed numeric
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  expected_count integer;
  saved_count integer;
begin
  if not public.is_admin(auth.uid()) then
    raise exception 'Admin access required.';
  end if;

  if p_official_winning_average_speed is null or p_official_winning_average_speed <= 0 then
    raise exception 'Official winning average speed must be greater than zero.';
  end if;

  expected_count := public.ensure_race_result_field_snapshot(p_race_id);

  select count(*) into saved_count
  from public.results result_row
  where result_row.race_id = p_race_id;

  if saved_count <> expected_count then
    raise exception 'Cannot publish results: % of % required driver rows are saved.', saved_count, expected_count;
  end if;

  if exists (
    select 1
    from public.results result_row
    left join public.race_driver_groups rg
      on rg.race_id = result_row.race_id
      and rg.driver_id = result_row.driver_id
    where result_row.race_id = p_race_id
      and rg.driver_id is null
  ) then
    raise exception 'Cannot publish results because a saved driver is outside the race field.';
  end if;

  update public.races
  set
    official_winning_average_speed = p_official_winning_average_speed,
    results_status = 'published',
    results_published_at = timezone('utc', now()),
    winner_profile_id = null,
    winner_source = 'auto',
    winner_is_manual_override = false,
    winner_auto_eligible_at = timezone('utc', now()) + interval '15 minutes',
    winner_set_at = null
  where id = p_race_id;

  perform public.refresh_driver_standings_from_published_results();
  return saved_count;
end;
$$;

revoke all on function public.publish_saved_race_results(bigint, numeric) from public, anon;
grant execute on function public.publish_saved_race_results(bigint, numeric) to authenticated;

create or replace function public.publish_race_results(
  p_race_id bigint,
  p_results jsonb,
  p_official_winning_average_speed numeric
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  distinct_driver_count integer;
  distinct_position_count integer;
  expected_count integer;
  maximum_position integer;
  minimum_position integer;
  payload_count integer;
  race_pick_format text;
begin
  if not public.is_admin(auth.uid()) then
    raise exception 'Admin access required.';
  end if;

  if jsonb_typeof(p_results) <> 'array' then
    raise exception 'Race results payload must be an array.';
  end if;

  if p_official_winning_average_speed is null or p_official_winning_average_speed <= 0 then
    raise exception 'Official winning average speed must be greater than zero.';
  end if;

  expected_count := public.ensure_race_result_field_snapshot(p_race_id);

  select r.pick_format into race_pick_format
  from public.races r
  where r.id = p_race_id;

  select
    count(*),
    count(distinct payload.driver_id),
    count(distinct payload.position),
    min(payload.position),
    max(payload.position)
    into
      payload_count,
      distinct_driver_count,
      distinct_position_count,
      minimum_position,
      maximum_position
  from jsonb_to_recordset(p_results) as payload(driver_id bigint, points integer, position integer);

  if payload_count = 0 or payload_count > expected_count then
    raise exception 'Cannot publish results: % official rows were supplied for a % driver snapshot.', payload_count, expected_count;
  end if;

  if race_pick_format = 'indy_500' and payload_count <> expected_count then
    raise exception 'Indianapolis 500 results require all % snapshotted drivers; % rows were supplied.', expected_count, payload_count;
  end if;

  if race_pick_format = 'standard' and expected_count - payload_count > 5 then
    raise exception 'Too many snapshotted drivers are absent from the official order (%). Review the pasted results before publishing.', expected_count - payload_count;
  end if;

  if distinct_driver_count <> payload_count then
    raise exception 'Cannot publish results because duplicate drivers were supplied.';
  end if;

  if exists (
    select 1
    from jsonb_to_recordset(p_results) as payload(driver_id bigint, points integer, position integer)
    where payload.driver_id is null
      or payload.points is null
      or payload.points < 0
      or payload.position is null
      or payload.position < 1
  ) then
    raise exception 'Every result requires a driver, a finishing position, and non-negative integer points.';
  end if;

  if distinct_position_count <> payload_count
    or minimum_position <> 1
    or maximum_position <> payload_count then
    raise exception 'Official finishing positions must be unique and contiguous from 1 through %.', payload_count;
  end if;

  if exists (
    select 1
    from jsonb_to_recordset(p_results) as payload(driver_id bigint, points integer, position integer)
    left join public.race_driver_groups rg
      on rg.race_id = p_race_id
      and rg.driver_id = payload.driver_id
    where rg.driver_id is null
  ) then
    raise exception 'Cannot publish results because a supplied driver is outside the race field.';
  end if;

  if exists (
    select required_group.group_number
    from generate_series(1, case when race_pick_format = 'indy_500' then 8 else 6 end)
      as required_group(group_number)
    where not exists (
      select 1
      from jsonb_to_recordset(p_results) as payload(driver_id bigint, points integer, position integer)
      join public.race_driver_groups rg
        on rg.race_id = p_race_id
        and rg.driver_id = payload.driver_id
      where rg.group_number = required_group.group_number
    )
  ) then
    raise exception 'Official results must include at least one participating driver from every pick group.';
  end if;

  delete from public.results
  where race_id = p_race_id;

  insert into public.results (race_id, driver_id, points)
  select p_race_id, payload.driver_id, payload.points
  from jsonb_to_recordset(p_results) as payload(driver_id bigint, points integer, position integer);

  insert into public.results (race_id, driver_id, points)
  select p_race_id, rg.driver_id, 0
  from public.race_driver_groups rg
  where rg.race_id = p_race_id
    and not exists (
      select 1
      from jsonb_to_recordset(p_results) as payload(driver_id bigint, points integer, position integer)
      where payload.driver_id = rg.driver_id
    );

  update public.races
  set
    official_winning_average_speed = p_official_winning_average_speed,
    results_status = 'published',
    results_published_at = timezone('utc', now()),
    winner_profile_id = null,
    winner_source = 'auto',
    winner_is_manual_override = false,
    winner_auto_eligible_at = timezone('utc', now()) + interval '15 minutes',
    winner_set_at = null
  where id = p_race_id;

  perform public.refresh_driver_standings_from_published_results();
  return expected_count;
end;
$$;

revoke all on function public.publish_race_results(bigint, jsonb, numeric) from public, anon;
grant execute on function public.publish_race_results(bigint, jsonb, numeric) to authenticated;

revoke all on function public.is_admin(uuid) from public, anon;
grant execute on function public.is_admin(uuid) to authenticated, service_role;

-- RLS
alter table public.profiles enable row level security;
alter table public.drivers enable row level security;
alter table public.races enable row level security;
alter table public.picks enable row level security;
alter table public.results enable row level security;
alter table public.race_driver_groups enable row level security;
alter table public.feedback_items enable row level security;
alter table public.pick_reminders enable row level security;

-- profiles policies
drop policy if exists profiles_select_self_or_admin on public.profiles;
create policy profiles_select_self_or_admin
on public.profiles
for select
to authenticated
using (id = auth.uid() or public.is_admin(auth.uid()));

drop policy if exists profiles_insert_self on public.profiles;
create policy profiles_insert_self
on public.profiles
for insert
to authenticated
with check (id = auth.uid() and role = 'participant');

drop policy if exists profiles_update_self_or_admin on public.profiles;
create policy profiles_update_self_or_admin
on public.profiles
for update
to authenticated
using (id = auth.uid() or public.is_admin(auth.uid()))
with check (id = auth.uid() or public.is_admin(auth.uid()));

-- drivers policies
drop policy if exists drivers_read_all on public.drivers;
create policy drivers_read_all
on public.drivers
for select
to authenticated
using (true);

drop policy if exists drivers_admin_write on public.drivers;
create policy drivers_admin_write
on public.drivers
for all
to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

-- races policies
drop policy if exists races_read_all on public.races;
create policy races_read_all
on public.races
for select
to authenticated
using (true);

drop policy if exists races_admin_write on public.races;
create policy races_admin_write
on public.races
for all
to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

-- picks policies
drop policy if exists picks_select_own_or_admin on public.picks;
create policy picks_select_own_or_admin
on public.picks
for select
to authenticated
using (user_id = auth.uid() or public.is_admin(auth.uid()));

drop policy if exists picks_insert_own on public.picks;
create policy picks_insert_own
on public.picks
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists picks_update_own_or_admin on public.picks;
create policy picks_update_own_or_admin
on public.picks
for update
to authenticated
using (user_id = auth.uid() or public.is_admin(auth.uid()))
with check (user_id = auth.uid() or public.is_admin(auth.uid()));

drop policy if exists picks_delete_own_or_admin on public.picks;
create policy picks_delete_own_or_admin
on public.picks
for delete
to authenticated
using (user_id = auth.uid() or public.is_admin(auth.uid()));

-- results policies
drop policy if exists results_read_all on public.results;
drop policy if exists results_read_published_or_admin on public.results;
create policy results_read_published_or_admin
on public.results
for select
to authenticated
using (
  public.is_admin(auth.uid())
  or exists (
    select 1
    from public.races r
    where r.id = results.race_id
      and r.results_status = 'published'
  )
);

drop policy if exists results_admin_write on public.results;
revoke insert, update, delete on table public.results from anon, authenticated;

-- race driver group snapshot policies
drop policy if exists race_driver_groups_read_authenticated on public.race_driver_groups;
create policy race_driver_groups_read_authenticated
on public.race_driver_groups
for select
to authenticated
using (true);

drop policy if exists race_driver_groups_admin_read on public.race_driver_groups;
create policy race_driver_groups_admin_read
on public.race_driver_groups
for select
to authenticated
using (public.is_admin(auth.uid()));

drop policy if exists race_driver_groups_admin_write on public.race_driver_groups;
create policy race_driver_groups_admin_write
on public.race_driver_groups
for all
to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

-- feedback policies
drop policy if exists feedback_items_select_own_or_admin on public.feedback_items;
create policy feedback_items_select_own_or_admin
on public.feedback_items
for select
to authenticated
using (user_id = auth.uid() or public.is_admin(auth.uid()));

drop policy if exists feedback_items_insert_own on public.feedback_items;
create policy feedback_items_insert_own
on public.feedback_items
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists feedback_items_update_admin on public.feedback_items;
create policy feedback_items_update_admin
on public.feedback_items
for update
to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists feedback_items_delete_admin on public.feedback_items;
create policy feedback_items_delete_admin
on public.feedback_items
for delete
to authenticated
using (public.is_admin(auth.uid()));

-- pick reminder policies
drop policy if exists pick_reminders_admin_read on public.pick_reminders;
create policy pick_reminders_admin_read
on public.pick_reminders
for select
to authenticated
using (public.is_admin(auth.uid()));
