// Generated by `npm run db:types` from the deployed Supabase PostgREST contract.
// Do not edit this file manually.
// Contract SHA-256: 184caa097167b4a65df0e9b05d3766e97151bbfe94db28bfb539df9a40cb3e55

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      "admin_audit_events": {
        Row: {
          "action": string
          "actor_profile_id": string | null
          "after_state": Json | null
          "before_state": Json | null
          "created_at": string
          "entity_id": string | null
          "entity_type": string
          "id": number
          "summary": string
        }
        Insert: {
          "action": string
          "actor_profile_id"?: string | null
          "after_state"?: Json | null
          "before_state"?: Json | null
          "created_at"?: string
          "entity_id"?: string | null
          "entity_type": string
          "id"?: number
          "summary": string
        }
        Update: {
          "action"?: string
          "actor_profile_id"?: string | null
          "after_state"?: Json | null
          "before_state"?: Json | null
          "created_at"?: string
          "entity_id"?: string | null
          "entity_type"?: string
          "id"?: number
          "summary"?: string
        }
        Relationships: [
          {
            foreignKeyName: "admin_audit_events_actor_profile_id_fkey"
            columns: ["actor_profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      "app_error_events": {
        Row: {
          "actor_profile_id": string | null
          "correlation_id": string
          "dedupe_key": string | null
          "error_code": string
          "first_seen_at": string
          "id": number
          "last_seen_at": string
          "occurrence_count": number
          "resolved_at": string | null
          "resolved_by": string | null
          "route": string
          "safe_context": Json
          "severity": string
          "status": string
          "subsystem": string
          "technical_summary": string
        }
        Insert: {
          "actor_profile_id"?: string | null
          "correlation_id": string
          "dedupe_key"?: string | null
          "error_code": string
          "first_seen_at"?: string
          "id"?: number
          "last_seen_at"?: string
          "occurrence_count"?: number
          "resolved_at"?: string | null
          "resolved_by"?: string | null
          "route": string
          "safe_context": Json
          "severity"?: string
          "status"?: string
          "subsystem": string
          "technical_summary": string
        }
        Update: {
          "actor_profile_id"?: string | null
          "correlation_id"?: string
          "dedupe_key"?: string | null
          "error_code"?: string
          "first_seen_at"?: string
          "id"?: number
          "last_seen_at"?: string
          "occurrence_count"?: number
          "resolved_at"?: string | null
          "resolved_by"?: string | null
          "route"?: string
          "safe_context"?: Json
          "severity"?: string
          "status"?: string
          "subsystem"?: string
          "technical_summary"?: string
        }
        Relationships: [
          {
            foreignKeyName: "app_error_events_actor_profile_id_fkey"
            columns: ["actor_profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "app_error_events_resolved_by_fkey"
            columns: ["resolved_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      "app_metadata": {
        Row: {
          "key": string
          "updated_at": string
          "value": string
        }
        Insert: {
          "key": string
          "updated_at"?: string
          "value": string
        }
        Update: {
          "key"?: string
          "updated_at"?: string
          "value"?: string
        }
        Relationships: []
      }
      "drivers": {
        Row: {
          "championship_points": number
          "created_at": string
          "current_standing": number
          "driver_name": string
          "group_number": number
          "id": number
          "image_url": string | null
          "is_active": boolean
          "opening_seed_standing": number | null
          "updated_at": string
        }
        Insert: {
          "championship_points"?: number
          "created_at"?: string
          "current_standing": number
          "driver_name": string
          "group_number": number
          "id"?: number
          "image_url"?: string | null
          "is_active"?: boolean
          "opening_seed_standing"?: number | null
          "updated_at"?: string
        }
        Update: {
          "championship_points"?: number
          "created_at"?: string
          "current_standing"?: number
          "driver_name"?: string
          "group_number"?: number
          "id"?: number
          "image_url"?: string | null
          "is_active"?: boolean
          "opening_seed_standing"?: number | null
          "updated_at"?: string
        }
        Relationships: []
      }
      "feedback_items": {
        Row: {
          "category": string
          "context_page": string | null
          "created_at": string
          "details": string
          "feedback_type": string
          "id": number
          "resolved_at": string | null
          "status": string
          "updated_at": string
          "user_id": string
        }
        Insert: {
          "category": string
          "context_page"?: string | null
          "created_at"?: string
          "details": string
          "feedback_type": string
          "id"?: number
          "resolved_at"?: string | null
          "status"?: string
          "updated_at"?: string
          "user_id": string
        }
        Update: {
          "category"?: string
          "context_page"?: string | null
          "created_at"?: string
          "details"?: string
          "feedback_type"?: string
          "id"?: number
          "resolved_at"?: string | null
          "status"?: string
          "updated_at"?: string
          "user_id"?: string
        }
        Relationships: [
          {
            foreignKeyName: "feedback_items_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      "hall_of_fame_entries": {
        Row: {
          "created_at": string
          "final_rank": number
          "id": number
          "race_breakdown": Json
          "season_id": number
          "team_name": string
          "total_points": number
        }
        Insert: {
          "created_at"?: string
          "final_rank": number
          "id"?: number
          "race_breakdown": Json
          "season_id": number
          "team_name": string
          "total_points": number
        }
        Update: {
          "created_at"?: string
          "final_rank"?: number
          "id"?: number
          "race_breakdown"?: Json
          "season_id"?: number
          "team_name"?: string
          "total_points"?: number
        }
        Relationships: [
          {
            foreignKeyName: "hall_of_fame_entries_season_id_fkey"
            columns: ["season_id"]
            isOneToOne: false
            referencedRelation: "hall_of_fame_seasons"
            referencedColumns: ["id"]
          },
        ]
      }
      "hall_of_fame_seasons": {
        Row: {
          "champion_team_name": string
          "champion_total_points": number
          "created_at": string
          "finalized_at": string
          "finalized_by": string | null
          "id": number
          "participant_count": number
          "race_count": number
          "season_year": number
          "updated_at": string
        }
        Insert: {
          "champion_team_name": string
          "champion_total_points": number
          "created_at"?: string
          "finalized_at"?: string
          "finalized_by"?: string | null
          "id"?: number
          "participant_count": number
          "race_count": number
          "season_year": number
          "updated_at"?: string
        }
        Update: {
          "champion_team_name"?: string
          "champion_total_points"?: number
          "created_at"?: string
          "finalized_at"?: string
          "finalized_by"?: string | null
          "id"?: number
          "participant_count"?: number
          "race_count"?: number
          "season_year"?: number
          "updated_at"?: string
        }
        Relationships: [
          {
            foreignKeyName: "hall_of_fame_seasons_finalized_by_fkey"
            columns: ["finalized_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      "job_runs": {
        Row: {
          "completed_at": string | null
          "created_at": string
          "error_message": string | null
          "id": number
          "job_name": string
          "started_at": string
          "status": string
          "summary": Json
        }
        Insert: {
          "completed_at"?: string | null
          "created_at"?: string
          "error_message"?: string | null
          "id"?: number
          "job_name": string
          "started_at"?: string
          "status"?: string
          "summary": Json
        }
        Update: {
          "completed_at"?: string | null
          "created_at"?: string
          "error_message"?: string | null
          "id"?: number
          "job_name"?: string
          "started_at"?: string
          "status"?: string
          "summary"?: Json
        }
        Relationships: []
      }
      "job_status": {
        Row: {
          "error_message": string | null
          "job_name": string
          "last_completed_at": string | null
          "last_started_at": string
          "run_count": number
          "run_token": string
          "status": string
          "summary": Json
          "updated_at": string
        }
        Insert: {
          "error_message"?: string | null
          "job_name": string
          "last_completed_at"?: string | null
          "last_started_at": string
          "run_count"?: number
          "run_token": string
          "status": string
          "summary": Json
          "updated_at"?: string
        }
        Update: {
          "error_message"?: string | null
          "job_name"?: string
          "last_completed_at"?: string | null
          "last_started_at"?: string
          "run_count"?: number
          "run_token"?: string
          "status"?: string
          "summary"?: Json
          "updated_at"?: string
        }
        Relationships: []
      }
      "league_seasons": {
        Row: {
          "activated_at": string | null
          "completed_at": string | null
          "created_at": string
          "display_name": string
          "id": number
          "registration_code_configured_at": string | null
          "roster_configured_at": string | null
          "rules_document_url": string | null
          "season_year": number
          "status": string
          "updated_at": string
        }
        Insert: {
          "activated_at"?: string | null
          "completed_at"?: string | null
          "created_at"?: string
          "display_name": string
          "id"?: number
          "registration_code_configured_at"?: string | null
          "roster_configured_at"?: string | null
          "rules_document_url"?: string | null
          "season_year": number
          "status"?: string
          "updated_at"?: string
        }
        Update: {
          "activated_at"?: string | null
          "completed_at"?: string | null
          "created_at"?: string
          "display_name"?: string
          "id"?: number
          "registration_code_configured_at"?: string | null
          "roster_configured_at"?: string | null
          "rules_document_url"?: string | null
          "season_year"?: number
          "status"?: string
          "updated_at"?: string
        }
        Relationships: []
      }
      "pick_reminders": {
        Row: {
          "attempt_count": number
          "channel": string
          "created_at": string
          "delivery_id": string | null
          "delivery_status": string
          "id": number
          "last_attempt_at": string | null
          "last_error": string | null
          "lease_expires_at": string | null
          "race_id": number
          "recipient": string
          "reminder_type": string
          "sent_at": string | null
          "updated_at": string
          "user_id": string
        }
        Insert: {
          "attempt_count"?: number
          "channel": string
          "created_at"?: string
          "delivery_id"?: string | null
          "delivery_status"?: string
          "id"?: number
          "last_attempt_at"?: string | null
          "last_error"?: string | null
          "lease_expires_at"?: string | null
          "race_id": number
          "recipient": string
          "reminder_type": string
          "sent_at"?: string | null
          "updated_at"?: string
          "user_id": string
        }
        Update: {
          "attempt_count"?: number
          "channel"?: string
          "created_at"?: string
          "delivery_id"?: string | null
          "delivery_status"?: string
          "id"?: number
          "last_attempt_at"?: string | null
          "last_error"?: string | null
          "lease_expires_at"?: string | null
          "race_id"?: number
          "recipient"?: string
          "reminder_type"?: string
          "sent_at"?: string | null
          "updated_at"?: string
          "user_id"?: string
        }
        Relationships: [
          {
            foreignKeyName: "pick_reminders_race_id_fkey"
            columns: ["race_id"]
            isOneToOne: false
            referencedRelation: "races"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pick_reminders_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      "pick_submission_versions": {
        Row: {
          "average_speed": number
          "driver_group1_id": number
          "driver_group2_id": number
          "driver_group3_id": number
          "driver_group4_id": number
          "driver_group5_id": number
          "driver_group6_id": number
          "driver_group7_id": number | null
          "driver_group8_id": number | null
          "id": number
          "pick_id": number | null
          "race_id": number
          "submission_version": number
          "submitted_at": string
          "user_id": string
        }
        Insert: {
          "average_speed": number
          "driver_group1_id": number
          "driver_group2_id": number
          "driver_group3_id": number
          "driver_group4_id": number
          "driver_group5_id": number
          "driver_group6_id": number
          "driver_group7_id"?: number | null
          "driver_group8_id"?: number | null
          "id"?: number
          "pick_id"?: number | null
          "race_id": number
          "submission_version": number
          "submitted_at"?: string
          "user_id": string
        }
        Update: {
          "average_speed"?: number
          "driver_group1_id"?: number
          "driver_group2_id"?: number
          "driver_group3_id"?: number
          "driver_group4_id"?: number
          "driver_group5_id"?: number
          "driver_group6_id"?: number
          "driver_group7_id"?: number | null
          "driver_group8_id"?: number | null
          "id"?: number
          "pick_id"?: number | null
          "race_id"?: number
          "submission_version"?: number
          "submitted_at"?: string
          "user_id"?: string
        }
        Relationships: [
          {
            foreignKeyName: "pick_submission_versions_driver_group1_id_fkey"
            columns: ["driver_group1_id"]
            isOneToOne: false
            referencedRelation: "drivers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pick_submission_versions_driver_group2_id_fkey"
            columns: ["driver_group2_id"]
            isOneToOne: false
            referencedRelation: "drivers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pick_submission_versions_driver_group3_id_fkey"
            columns: ["driver_group3_id"]
            isOneToOne: false
            referencedRelation: "drivers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pick_submission_versions_driver_group4_id_fkey"
            columns: ["driver_group4_id"]
            isOneToOne: false
            referencedRelation: "drivers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pick_submission_versions_driver_group5_id_fkey"
            columns: ["driver_group5_id"]
            isOneToOne: false
            referencedRelation: "drivers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pick_submission_versions_driver_group6_id_fkey"
            columns: ["driver_group6_id"]
            isOneToOne: false
            referencedRelation: "drivers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pick_submission_versions_driver_group7_id_fkey"
            columns: ["driver_group7_id"]
            isOneToOne: false
            referencedRelation: "drivers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pick_submission_versions_driver_group8_id_fkey"
            columns: ["driver_group8_id"]
            isOneToOne: false
            referencedRelation: "drivers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pick_submission_versions_pick_id_fkey"
            columns: ["pick_id"]
            isOneToOne: false
            referencedRelation: "picks"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pick_submission_versions_race_id_fkey"
            columns: ["race_id"]
            isOneToOne: false
            referencedRelation: "races"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pick_submission_versions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      "picks": {
        Row: {
          "average_speed": number
          "created_at": string
          "driver_group1_id": number
          "driver_group2_id": number
          "driver_group3_id": number
          "driver_group4_id": number
          "driver_group5_id": number
          "driver_group6_id": number
          "driver_group7_id": number | null
          "driver_group8_id": number | null
          "id": number
          "race_id": number
          "updated_at": string
          "user_id": string
        }
        Insert: {
          "average_speed": number
          "created_at"?: string
          "driver_group1_id": number
          "driver_group2_id": number
          "driver_group3_id": number
          "driver_group4_id": number
          "driver_group5_id": number
          "driver_group6_id": number
          "driver_group7_id"?: number | null
          "driver_group8_id"?: number | null
          "id"?: number
          "race_id": number
          "updated_at"?: string
          "user_id": string
        }
        Update: {
          "average_speed"?: number
          "created_at"?: string
          "driver_group1_id"?: number
          "driver_group2_id"?: number
          "driver_group3_id"?: number
          "driver_group4_id"?: number
          "driver_group5_id"?: number
          "driver_group6_id"?: number
          "driver_group7_id"?: number | null
          "driver_group8_id"?: number | null
          "id"?: number
          "race_id"?: number
          "updated_at"?: string
          "user_id"?: string
        }
        Relationships: [
          {
            foreignKeyName: "picks_driver_group1_id_fkey"
            columns: ["driver_group1_id"]
            isOneToOne: false
            referencedRelation: "drivers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "picks_driver_group2_id_fkey"
            columns: ["driver_group2_id"]
            isOneToOne: false
            referencedRelation: "drivers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "picks_driver_group3_id_fkey"
            columns: ["driver_group3_id"]
            isOneToOne: false
            referencedRelation: "drivers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "picks_driver_group4_id_fkey"
            columns: ["driver_group4_id"]
            isOneToOne: false
            referencedRelation: "drivers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "picks_driver_group5_id_fkey"
            columns: ["driver_group5_id"]
            isOneToOne: false
            referencedRelation: "drivers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "picks_driver_group6_id_fkey"
            columns: ["driver_group6_id"]
            isOneToOne: false
            referencedRelation: "drivers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "picks_driver_group7_id_fkey"
            columns: ["driver_group7_id"]
            isOneToOne: false
            referencedRelation: "drivers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "picks_driver_group8_id_fkey"
            columns: ["driver_group8_id"]
            isOneToOne: false
            referencedRelation: "drivers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "picks_race_id_fkey"
            columns: ["race_id"]
            isOneToOne: false
            referencedRelation: "races"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "picks_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      "profiles": {
        Row: {
          "created_at": string
          "full_name": string | null
          "id": string
          "is_active": boolean
          "role": string
          "team_name": string
          "updated_at": string
        }
        Insert: {
          "created_at"?: string
          "full_name"?: string | null
          "id": string
          "is_active"?: boolean
          "role"?: string
          "team_name": string
          "updated_at"?: string
        }
        Update: {
          "created_at"?: string
          "full_name"?: string | null
          "id"?: string
          "is_active"?: boolean
          "role"?: string
          "team_name"?: string
          "updated_at"?: string
        }
        Relationships: []
      }
      "race_driver_groups": {
        Row: {
          "created_at": string
          "driver_id": number
          "group_number": number
          "qualifying_position": number | null
          "race_id": number
          "updated_at": string
        }
        Insert: {
          "created_at"?: string
          "driver_id"?: number
          "group_number": number
          "qualifying_position"?: number | null
          "race_id"?: number
          "updated_at"?: string
        }
        Update: {
          "created_at"?: string
          "driver_id"?: number
          "group_number"?: number
          "qualifying_position"?: number | null
          "race_id"?: number
          "updated_at"?: string
        }
        Relationships: [
          {
            foreignKeyName: "race_driver_groups_driver_id_fkey"
            columns: ["driver_id"]
            isOneToOne: true
            referencedRelation: "drivers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "race_driver_groups_race_id_fkey"
            columns: ["race_id"]
            isOneToOne: true
            referencedRelation: "races"
            referencedColumns: ["id"]
          },
        ]
      }
      "races": {
        Row: {
          "archived_at": string | null
          "created_at": string
          "field_frozen_at": string | null
          "id": number
          "is_archived": boolean
          "official_winning_average_speed": number | null
          "payout": number
          "pick_format": string
          "pick_window_key": string
          "qualifying_start_at": string
          "race_date": string
          "race_name": string
          "results_published_at": string | null
          "results_status": string
          "round_number": number
          "season_id": number
          "title_image_url": string | null
          "updated_at": string
          "winner_auto_eligible_at": string | null
          "winner_is_manual_override": boolean
          "winner_profile_id": string | null
          "winner_set_at": string | null
          "winner_source": string
        }
        Insert: {
          "archived_at"?: string | null
          "created_at"?: string
          "field_frozen_at"?: string | null
          "id"?: number
          "is_archived"?: boolean
          "official_winning_average_speed"?: number | null
          "payout"?: number
          "pick_format"?: string
          "pick_window_key"?: string
          "qualifying_start_at": string
          "race_date": string
          "race_name": string
          "results_published_at"?: string | null
          "results_status"?: string
          "round_number": number
          "season_id": number
          "title_image_url"?: string | null
          "updated_at"?: string
          "winner_auto_eligible_at"?: string | null
          "winner_is_manual_override"?: boolean
          "winner_profile_id"?: string | null
          "winner_set_at"?: string | null
          "winner_source"?: string
        }
        Update: {
          "archived_at"?: string | null
          "created_at"?: string
          "field_frozen_at"?: string | null
          "id"?: number
          "is_archived"?: boolean
          "official_winning_average_speed"?: number | null
          "payout"?: number
          "pick_format"?: string
          "pick_window_key"?: string
          "qualifying_start_at"?: string
          "race_date"?: string
          "race_name"?: string
          "results_published_at"?: string | null
          "results_status"?: string
          "round_number"?: number
          "season_id"?: number
          "title_image_url"?: string | null
          "updated_at"?: string
          "winner_auto_eligible_at"?: string | null
          "winner_is_manual_override"?: boolean
          "winner_profile_id"?: string | null
          "winner_set_at"?: string | null
          "winner_source"?: string
        }
        Relationships: [
          {
            foreignKeyName: "races_season_id_fkey"
            columns: ["season_id"]
            isOneToOne: false
            referencedRelation: "league_seasons"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "races_winner_profile_id_fkey"
            columns: ["winner_profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      "registration_attempt_limits": {
        Row: {
          "attempt_count": number
          "key_hash": string
          "updated_at": string
          "window_started_at": string
        }
        Insert: {
          "attempt_count"?: number
          "key_hash": string
          "updated_at"?: string
          "window_started_at"?: string
        }
        Update: {
          "attempt_count"?: number
          "key_hash"?: string
          "updated_at"?: string
          "window_started_at"?: string
        }
        Relationships: []
      }
      "results": {
        Row: {
          "created_at": string
          "driver_id": number
          "id": number
          "points": number
          "race_id": number
          "updated_at": string
        }
        Insert: {
          "created_at"?: string
          "driver_id": number
          "id"?: number
          "points": number
          "race_id": number
          "updated_at"?: string
        }
        Update: {
          "created_at"?: string
          "driver_id"?: number
          "id"?: number
          "points"?: number
          "race_id"?: number
          "updated_at"?: string
        }
        Relationships: [
          {
            foreignKeyName: "results_driver_id_fkey"
            columns: ["driver_id"]
            isOneToOne: false
            referencedRelation: "drivers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "results_race_id_fkey"
            columns: ["race_id"]
            isOneToOne: false
            referencedRelation: "races"
            referencedColumns: ["id"]
          },
        ]
      }
      "season_participants": {
        Row: {
          "created_at": string
          "decided_at": string
          "profile_id": string
          "registered_at": string | null
          "season_id": number
          "status": string
          "updated_at": string
        }
        Insert: {
          "created_at"?: string
          "decided_at"?: string
          "profile_id": string
          "registered_at"?: string | null
          "season_id"?: number
          "status": string
          "updated_at"?: string
        }
        Update: {
          "created_at"?: string
          "decided_at"?: string
          "profile_id"?: string
          "registered_at"?: string | null
          "season_id"?: number
          "status"?: string
          "updated_at"?: string
        }
        Relationships: [
          {
            foreignKeyName: "season_participants_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "season_participants_season_id_fkey"
            columns: ["season_id"]
            isOneToOne: true
            referencedRelation: "league_seasons"
            referencedColumns: ["id"]
          },
        ]
      }
      "season_registration_secrets": {
        Row: {
          "created_at": string
          "invite_code_hash": string
          "season_id": number
          "updated_at": string
          "updated_by": string | null
        }
        Insert: {
          "created_at"?: string
          "invite_code_hash": string
          "season_id"?: number
          "updated_at"?: string
          "updated_by"?: string | null
        }
        Update: {
          "created_at"?: string
          "invite_code_hash"?: string
          "season_id"?: number
          "updated_at"?: string
          "updated_by"?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "season_registration_secrets_season_id_fkey"
            columns: ["season_id"]
            isOneToOne: true
            referencedRelation: "league_seasons"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "season_registration_secrets_updated_by_fkey"
            columns: ["updated_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      "season_restore_points": {
        Row: {
          "checksum": string
          "created_at": string
          "created_by": string | null
          "format_version": number
          "id": string
          "label": string
          "retention_key": string | null
          "row_counts": Json
          "schema_version": string
          "season_id": number
          "season_year": number
          "snapshot": Json
          "snapshot_bytes": number
          "source": string
        }
        Insert: {
          "checksum": string
          "created_at"?: string
          "created_by"?: string | null
          "format_version"?: number
          "id"?: string
          "label": string
          "retention_key"?: string | null
          "row_counts": Json
          "schema_version": string
          "season_id": number
          "season_year": number
          "snapshot": Json
          "snapshot_bytes"?: number
          "source": string
        }
        Update: {
          "checksum"?: string
          "created_at"?: string
          "created_by"?: string | null
          "format_version"?: number
          "id"?: string
          "label"?: string
          "retention_key"?: string | null
          "row_counts"?: Json
          "schema_version"?: string
          "season_id"?: number
          "season_year"?: number
          "snapshot"?: Json
          "snapshot_bytes"?: number
          "source"?: string
        }
        Relationships: [
          {
            foreignKeyName: "season_restore_points_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "season_restore_points_season_id_fkey"
            columns: ["season_id"]
            isOneToOne: false
            referencedRelation: "league_seasons"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: { [_ in never]: never }
    Functions: {
      "activate_league_season": {
        Args: {
          "p_season_id": number
        }
        Returns: Json
      }
      "admin_update_participant": {
        Args: {
          "p_account_eligible": boolean
          "p_force_removal"?: boolean | null
          "p_full_name": string
          "p_profile_id": string
          "p_season_registered": boolean
          "p_team_name": string
        }
        Returns: Json
      }
      "build_season_recovery_snapshot": {
        Args: {
          "p_season_id": number
        }
        Returns: Json
      }
      "claim_pick_reminder_delivery": {
        Args: {
          "p_channel": string
          "p_race_id": number
          "p_recipient": string
          "p_reminder_type": string
          "p_user_id": string
        }
        Returns: Json
      }
      "consume_registration_attempt": {
        Args: {
          "p_key_hashes": string[]
          "p_max_attempts"?: number | null
          "p_window_seconds"?: number | null
        }
        Returns: Json
      }
      "correct_pick_window_qualifying_start": {
        Args: {
          "p_qualifying_start_at": string
          "p_race_id": number
        }
        Returns: Json
      }
      "create_league_season": {
        Args: {
          "p_invite_code": string
          "p_season_year": number
        }
        Returns: Json
      }
      "create_season_restore_point": {
        Args: {
          "p_label": string
          "p_season_id": number
          "p_source"?: string | null
        }
        Returns: Json
      }
      "create_season_restore_point_v2": {
        Args: {
          "p_label": string
          "p_retention_key"?: string | null
          "p_season_id": number
          "p_source"?: string | null
        }
        Returns: Json
      }
      "ensure_race_pick_field_snapshot": {
        Args: {
          "p_race_id": number
        }
        Returns: Json
      }
      "ensure_race_result_field_snapshot": {
        Args: {
          "p_race_id": number
        }
        Returns: Json
      }
      "finalize_hall_of_fame_season": {
        Args: {
          "p_entries": Json
          "p_race_count": number
          "p_season_year": number
        }
        Returns: Json
      }
      "finish_job_run": {
        Args: {
          "p_error_message"?: string | null
          "p_job_run_id": number
          "p_status": string
          "p_summary"?: Json | null
        }
        Returns: Json
      }
      "finish_job_status": {
        Args: {
          "p_error_message"?: string | null
          "p_job_name": string
          "p_record_event"?: boolean | null
          "p_run_token": string
          "p_status": string
          "p_summary"?: Json | null
        }
        Returns: Json
      }
      "get_app_health_contract": {
        Args: {
          [_ in never]: never
        }
        Returns: Json
      }
      "import_season_restore_point": {
        Args: {
          "p_document": Json
        }
        Returns: Json
      }
      "is_admin": {
        Args: {
          "uid": string
        }
        Returns: Json
      }
      "is_registered_for_season": {
        Args: {
          "p_profile_id": string
          "p_season_id": number
        }
        Returns: Json
      }
      "jsonb_array_difference_count": {
        Args: {
          "p_left": Json
          "p_right": Json
        }
        Returns: Json
      }
      "pick_window_opens_at": {
        Args: {
          "p_race_id": number
        }
        Returns: string
      }
      "preview_season_restore_point": {
        Args: {
          "p_restore_point_id": string
        }
        Returns: Json
      }
      "prune_app_error_events": {
        Args: {
          [_ in never]: never
        }
        Returns: Json
      }
      "prune_job_run_history": {
        Args: {
          [_ in never]: never
        }
        Returns: Json
      }
      "prune_season_restore_points": {
        Args: {
          "p_season_id": number
        }
        Returns: Json
      }
      "publish_race_results": {
        Args: {
          "p_official_winning_average_speed": number
          "p_race_id": number
          "p_results": Json
        }
        Returns: Json
      }
      "publish_saved_race_results": {
        Args: {
          "p_official_winning_average_speed": number
          "p_race_id": number
        }
        Returns: Json
      }
      "record_app_error_event": {
        Args: {
          "p_actor_profile_id"?: string | null
          "p_correlation_id": string
          "p_error_code": string
          "p_route": string
          "p_safe_context"?: Json | null
          "p_severity": string
          "p_subsystem": string
          "p_technical_summary": string
        }
        Returns: Json
      }
      "refresh_driver_standings_from_published_results": {
        Args: {
          [_ in never]: never
        }
        Returns: Json
      }
      "register_profile_for_season_with_code": {
        Args: {
          "p_invite_code": string
          "p_profile_id": string
          "p_season_id": number
        }
        Returns: Json
      }
      "replace_indy_500_qualifying_order": {
        Args: {
          "p_race_id": number
          "p_rows": Json
        }
        Returns: Json
      }
      "resolve_app_error_event": {
        Args: {
          "p_event_id": number
        }
        Returns: Json
      }
      "restore_season_from_restore_point": {
        Args: {
          "p_confirmation_year": number
          "p_restore_point_id": string
        }
        Returns: Json
      }
      "restore_season_from_restore_point_v2": {
        Args: {
          "p_confirmation_year": number
          "p_restore_point_id": string
        }
        Returns: Json
      }
      "save_race_result_draft": {
        Args: {
          "p_driver_id": number
          "p_points": number
          "p_race_id": number
        }
        Returns: Json
      }
      "save_weekly_pick": {
        Args: {
          "p_average_speed": number
          "p_driver_ids": number[]
          "p_race_id": number
        }
        Returns: Json
      }
      "season_recovery_comparable_rows": {
        Args: {
          "p_snapshot": Json
          "p_table_key": string
        }
        Returns: Json
      }
      "season_recovery_row_counts": {
        Args: {
          "p_snapshot": Json
        }
        Returns: Json
      }
      "set_active_season_participation": {
        Args: {
          "p_register": boolean
        }
        Returns: Json
      }
      "set_league_season_invite_code": {
        Args: {
          "p_invite_code": string
          "p_season_id": number
        }
        Returns: Json
      }
      "start_job_run": {
        Args: {
          "p_job_name": string
        }
        Returns: Json
      }
      "start_job_status": {
        Args: {
          "p_job_name": string
        }
        Returns: Json
      }
      "sync_opening_driver_roster": {
        Args: {
          "p_rows": Json
          "p_season_id": number
        }
        Returns: Json
      }
      "validate_pick_reminder_delivery": {
        Args: {
          "p_reminder_id": number
        }
        Returns: Json
      }
      "validate_season_invite_code": {
        Args: {
          "p_invite_code": string
          "p_season_id": number
        }
        Returns: Json
      }
      "write_admin_audit_event": {
        Args: {
          "p_action": string
          "p_after_state"?: Json | null
          "p_before_state"?: Json | null
          "p_entity_id": string
          "p_entity_type": string
          "p_summary": string
        }
        Returns: Json
      }
    }
    Enums: { [_ in never]: never }
    CompositeTypes: { [_ in never]: never }
  }
};

type PublicSchema = Database["public"];

export type Tables<
  TableName extends keyof PublicSchema["Tables"]
> = PublicSchema["Tables"][TableName]["Row"];

export type TablesInsert<
  TableName extends keyof PublicSchema["Tables"]
> = PublicSchema["Tables"][TableName]["Insert"];

export type TablesUpdate<
  TableName extends keyof PublicSchema["Tables"]
> = PublicSchema["Tables"][TableName]["Update"];

export type FunctionArgs<
  FunctionName extends keyof PublicSchema["Functions"]
> = PublicSchema["Functions"][FunctionName]["Args"];
