-- Make participant pick saves atomic, preserve submission versions, and add guided season recovery.

begin;

alter table public.feedback_items
add column if not exists status text not null default 'new';

alter table public.feedback_items
add column if not exists resolved_at timestamptz;

alter table public.feedback_items
drop constraint if exists feedback_items_status_check;

alter table public.feedback_items
add constraint feedback_items_status_check
check (status in ('new', 'in_review', 'resolved'));

create index if not exists idx_feedback_items_status_created
on public.feedback_items(status, created_at desc);

create table if not exists public.pick_submission_versions (
  id bigint generated by default as identity primary key,
  pick_id bigint references public.picks(id) on delete set null,
  user_id uuid not null references public.profiles(id) on delete cascade,
  race_id bigint not null references public.races(id) on delete cascade,
  submission_version integer not null check (submission_version > 0),
  average_speed numeric(7,3) not null check (average_speed > 0 and average_speed <= 300),
  driver_group1_id bigint not null references public.drivers(id),
  driver_group2_id bigint not null references public.drivers(id),
  driver_group3_id bigint not null references public.drivers(id),
  driver_group4_id bigint not null references public.drivers(id),
  driver_group5_id bigint not null references public.drivers(id),
  driver_group6_id bigint not null references public.drivers(id),
  driver_group7_id bigint references public.drivers(id),
  driver_group8_id bigint references public.drivers(id),
  submitted_at timestamptz not null default timezone('utc', now()),
  unique (user_id, race_id, submission_version)
);

create index if not exists idx_pick_submission_versions_user_race
on public.pick_submission_versions(user_id, race_id, submission_version desc);

create index if not exists idx_pick_submission_versions_race
on public.pick_submission_versions(race_id, submitted_at desc);

insert into public.pick_submission_versions (
  pick_id,
  user_id,
  race_id,
  submission_version,
  average_speed,
  driver_group1_id,
  driver_group2_id,
  driver_group3_id,
  driver_group4_id,
  driver_group5_id,
  driver_group6_id,
  driver_group7_id,
  driver_group8_id,
  submitted_at
)
select
  pick.id,
  pick.user_id,
  pick.race_id,
  1,
  pick.average_speed,
  pick.driver_group1_id,
  pick.driver_group2_id,
  pick.driver_group3_id,
  pick.driver_group4_id,
  pick.driver_group5_id,
  pick.driver_group6_id,
  pick.driver_group7_id,
  pick.driver_group8_id,
  pick.updated_at
from public.picks pick
where not exists (
  select 1
  from public.pick_submission_versions version
  where version.user_id = pick.user_id
    and version.race_id = pick.race_id
);

create or replace function public.record_pick_submission_version()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  next_version integer;
begin
  if current_setting('mound_hounds.restore_mode', true) = 'on' then
    return new;
  end if;

  select coalesce(max(version.submission_version), 0) + 1
  into next_version
  from public.pick_submission_versions version
  where version.user_id = new.user_id
    and version.race_id = new.race_id;

  insert into public.pick_submission_versions (
    pick_id,
    user_id,
    race_id,
    submission_version,
    average_speed,
    driver_group1_id,
    driver_group2_id,
    driver_group3_id,
    driver_group4_id,
    driver_group5_id,
    driver_group6_id,
    driver_group7_id,
    driver_group8_id,
    submitted_at
  )
  values (
    new.id,
    new.user_id,
    new.race_id,
    next_version,
    new.average_speed,
    new.driver_group1_id,
    new.driver_group2_id,
    new.driver_group3_id,
    new.driver_group4_id,
    new.driver_group5_id,
    new.driver_group6_id,
    new.driver_group7_id,
    new.driver_group8_id,
    new.updated_at
  );

  return new;
end;
$$;

drop trigger if exists trg_record_pick_submission_version on public.picks;
create trigger trg_record_pick_submission_version
after insert or update on public.picks
for each row execute function public.record_pick_submission_version();

revoke all on function public.record_pick_submission_version() from public, anon, authenticated;

create or replace function public.save_weekly_pick(
  p_race_id bigint,
  p_average_speed numeric,
  p_driver_ids bigint[]
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
  expected_group_count integer;
  next_race_id bigint;
  race_name text;
  saved_pick public.picks%rowtype;
  saved_race_count integer;
  selected_race public.races%rowtype;
  submission_version integer;
  window_race_count integer;
begin
  if current_user_id is null then
    raise exception 'Authentication required.';
  end if;

  if p_average_speed is null or p_average_speed <= 0 or p_average_speed > 300 then
    raise exception 'Enter an average speed between 0 and 300 MPH.';
  end if;

  select * into selected_race
  from public.races
  where id = p_race_id;

  if selected_race.id is null then
    raise exception 'Selected race was not found.';
  end if;

  expected_group_count := case
    when selected_race.pick_format = 'indy_500' then 8
    else 6
  end;

  if p_driver_ids is null
    or array_length(p_driver_ids, 1) is distinct from expected_group_count
    or array_position(p_driver_ids, null) is not null then
    raise exception 'Select one driver from each of the % groups.', expected_group_count;
  end if;

  if (
    select count(distinct driver_id)
    from unnest(p_driver_ids) selected(driver_id)
  ) <> expected_group_count then
    raise exception 'Select a different driver in each group.';
  end if;

  insert into public.picks (
    user_id,
    race_id,
    average_speed,
    driver_group1_id,
    driver_group2_id,
    driver_group3_id,
    driver_group4_id,
    driver_group5_id,
    driver_group6_id,
    driver_group7_id,
    driver_group8_id
  )
  values (
    current_user_id,
    selected_race.id,
    p_average_speed,
    p_driver_ids[1],
    p_driver_ids[2],
    p_driver_ids[3],
    p_driver_ids[4],
    p_driver_ids[5],
    p_driver_ids[6],
    case when expected_group_count = 8 then p_driver_ids[7] else null end,
    case when expected_group_count = 8 then p_driver_ids[8] else null end
  )
  on conflict (user_id, race_id) do update
  set
    average_speed = excluded.average_speed,
    driver_group1_id = excluded.driver_group1_id,
    driver_group2_id = excluded.driver_group2_id,
    driver_group3_id = excluded.driver_group3_id,
    driver_group4_id = excluded.driver_group4_id,
    driver_group5_id = excluded.driver_group5_id,
    driver_group6_id = excluded.driver_group6_id,
    driver_group7_id = excluded.driver_group7_id,
    driver_group8_id = excluded.driver_group8_id
  returning * into saved_pick;

  select max(version.submission_version)
  into submission_version
  from public.pick_submission_versions version
  where version.user_id = current_user_id
    and version.race_id = selected_race.id;

  select count(*)
  into window_race_count
  from public.races race
  where race.season_id = selected_race.season_id
    and race.pick_window_key = selected_race.pick_window_key
    and race.is_archived = false;

  select count(*)
  into saved_race_count
  from public.picks pick
  join public.races race on race.id = pick.race_id
  where pick.user_id = current_user_id
    and race.season_id = selected_race.season_id
    and race.pick_window_key = selected_race.pick_window_key
    and race.is_archived = false;

  select race.id
  into next_race_id
  from public.races race
  where race.season_id = selected_race.season_id
    and race.pick_window_key = selected_race.pick_window_key
    and race.is_archived = false
    and not exists (
      select 1
      from public.picks pick
      where pick.user_id = current_user_id
        and pick.race_id = race.id
    )
  order by race.round_number, race.id
  limit 1;

  select race.race_name
  into race_name
  from public.races race
  where race.id = next_race_id;

  return jsonb_build_object(
    'pickId', saved_pick.id,
    'raceId', saved_pick.race_id,
    'updatedAt', saved_pick.updated_at,
    'submissionVersion', submission_version,
    'savedRaceCount', saved_race_count,
    'windowRaceCount', window_race_count,
    'nextRaceId', next_race_id,
    'message',
      case
        when next_race_id is not null then
          format('%s picks saved. Complete %s next.', selected_race.race_name, race_name)
        when window_race_count > 1 then
          'Both doubleheader race submissions are saved.'
        else
          'Your picks are saved.'
      end
  );
end;
$$;

revoke all on function public.save_weekly_pick(bigint, numeric, bigint[])
from public, anon;
grant execute on function public.save_weekly_pick(bigint, numeric, bigint[])
to authenticated;

alter table public.pick_submission_versions enable row level security;

grant select on table public.pick_submission_versions to authenticated;

drop policy if exists pick_submission_versions_read_own_or_admin
on public.pick_submission_versions;
create policy pick_submission_versions_read_own_or_admin
on public.pick_submission_versions
for select
to authenticated
using (user_id = auth.uid() or public.is_admin(auth.uid()));

create table if not exists public.season_restore_points (
  id uuid primary key default extensions.gen_random_uuid(),
  season_id bigint not null references public.league_seasons(id) on delete restrict,
  season_year integer not null check (season_year between 2000 and 2100),
  label text not null check (length(trim(label)) between 1 and 160),
  source text not null check (source in ('automatic', 'manual', 'pre_restore', 'uploaded')),
  schema_version text not null,
  format_version integer not null default 1 check (format_version = 1),
  row_counts jsonb not null check (jsonb_typeof(row_counts) = 'object'),
  snapshot jsonb not null check (jsonb_typeof(snapshot) = 'object'),
  checksum text not null check (length(checksum) = 64),
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_season_restore_points_season_created
on public.season_restore_points(season_id, created_at desc);

create or replace function public.prevent_season_restore_point_mutation()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  raise exception 'Season restore points are immutable.';
end;
$$;

drop trigger if exists trg_prevent_season_restore_point_mutation
on public.season_restore_points;
create trigger trg_prevent_season_restore_point_mutation
before update or delete on public.season_restore_points
for each row execute function public.prevent_season_restore_point_mutation();

revoke all on function public.prevent_season_restore_point_mutation()
from public, anon, authenticated;

create or replace function public.build_season_recovery_snapshot(p_season_id bigint)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  hall_of_fame_snapshot jsonb;
  selected_season public.league_seasons%rowtype;
begin
  select * into selected_season
  from public.league_seasons
  where id = p_season_id;

  if selected_season.id is null then
    raise exception 'Selected season was not found.';
  end if;

  select jsonb_build_object(
    'season',
    to_jsonb(hall),
    'entries',
    coalesce(
      (
        select jsonb_agg(to_jsonb(entry) order by entry.final_rank, entry.id)
        from public.hall_of_fame_entries entry
        where entry.season_id = hall.id
      ),
      '[]'::jsonb
    )
  )
  into hall_of_fame_snapshot
  from public.hall_of_fame_seasons hall
  where hall.season_year = selected_season.season_year;

  return jsonb_build_object(
    'format',
    'mound-hounds-season-backup',
    'formatVersion',
    1,
    'season',
    to_jsonb(selected_season),
    'profiles',
    coalesce(
      (
        select jsonb_agg(
          jsonb_build_object(
            'id', profile.id,
            'full_name', profile.full_name,
            'team_name', profile.team_name,
            'role', profile.role,
            'is_active', profile.is_active
          )
          order by profile.id
        )
        from public.profiles profile
        where exists (
          select 1
          from public.season_participants participant
          where participant.season_id = selected_season.id
            and participant.profile_id = profile.id
        )
      ),
      '[]'::jsonb
    ),
    'participants',
    coalesce(
      (
        select jsonb_agg(to_jsonb(participant) order by participant.profile_id)
        from public.season_participants participant
        where participant.season_id = selected_season.id
      ),
      '[]'::jsonb
    ),
    'drivers',
    coalesce(
      (
        select jsonb_agg(to_jsonb(driver) order by driver.id)
        from public.drivers driver
      ),
      '[]'::jsonb
    ),
    'races',
    coalesce(
      (
        select jsonb_agg(to_jsonb(race) order by race.round_number, race.id)
        from public.races race
        where race.season_id = selected_season.id
      ),
      '[]'::jsonb
    ),
    'raceDriverGroups',
    coalesce(
      (
        select jsonb_agg(
          to_jsonb(race_group)
          order by race_group.race_id, race_group.group_number, race_group.driver_id
        )
        from public.race_driver_groups race_group
        join public.races race on race.id = race_group.race_id
        where race.season_id = selected_season.id
      ),
      '[]'::jsonb
    ),
    'picks',
    coalesce(
      (
        select jsonb_agg(to_jsonb(pick) order by pick.race_id, pick.user_id)
        from public.picks pick
        join public.races race on race.id = pick.race_id
        where race.season_id = selected_season.id
      ),
      '[]'::jsonb
    ),
    'pickSubmissionVersions',
    coalesce(
      (
        select jsonb_agg(
          to_jsonb(version)
          order by version.race_id, version.user_id, version.submission_version
        )
        from public.pick_submission_versions version
        join public.races race on race.id = version.race_id
        where race.season_id = selected_season.id
      ),
      '[]'::jsonb
    ),
    'results',
    coalesce(
      (
        select jsonb_agg(to_jsonb(result_row) order by result_row.race_id, result_row.driver_id)
        from public.results result_row
        join public.races race on race.id = result_row.race_id
        where race.season_id = selected_season.id
      ),
      '[]'::jsonb
    ),
    'hallOfFame',
    hall_of_fame_snapshot
  );
end;
$$;

revoke all on function public.build_season_recovery_snapshot(bigint)
from public, anon, authenticated;

create or replace function public.season_recovery_row_counts(p_snapshot jsonb)
returns jsonb
language sql
immutable
set search_path = public
as $$
  select jsonb_build_object(
    'profiles', jsonb_array_length(coalesce(p_snapshot->'profiles', '[]'::jsonb)),
    'participants', jsonb_array_length(coalesce(p_snapshot->'participants', '[]'::jsonb)),
    'drivers', jsonb_array_length(coalesce(p_snapshot->'drivers', '[]'::jsonb)),
    'races', jsonb_array_length(coalesce(p_snapshot->'races', '[]'::jsonb)),
    'raceDriverGroups', jsonb_array_length(coalesce(p_snapshot->'raceDriverGroups', '[]'::jsonb)),
    'picks', jsonb_array_length(coalesce(p_snapshot->'picks', '[]'::jsonb)),
    'pickSubmissionVersions', jsonb_array_length(coalesce(p_snapshot->'pickSubmissionVersions', '[]'::jsonb)),
    'results', jsonb_array_length(coalesce(p_snapshot->'results', '[]'::jsonb)),
    'hallOfFameEntries',
      case
        when jsonb_typeof(p_snapshot->'hallOfFame') = 'object'
          then jsonb_array_length(coalesce(p_snapshot->'hallOfFame'->'entries', '[]'::jsonb))
        else 0
      end
  );
$$;

revoke all on function public.season_recovery_row_counts(jsonb)
from public, anon, authenticated;

create or replace function public.create_season_restore_point(
  p_season_id bigint,
  p_label text,
  p_source text default 'manual'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  checksum_value text;
  inserted_point public.season_restore_points%rowtype;
  row_counts_value jsonb;
  schema_version_value text;
  selected_season public.league_seasons%rowtype;
  snapshot_value jsonb;
begin
  if coalesce(auth.role(), '') <> 'service_role' and not public.is_admin(auth.uid()) then
    raise exception 'Admin access required.';
  end if;

  if p_source not in ('automatic', 'manual', 'pre_restore', 'uploaded') then
    raise exception 'Invalid restore-point source.';
  end if;

  if length(trim(coalesce(p_label, ''))) not between 1 and 160 then
    raise exception 'Restore-point label must be between 1 and 160 characters.';
  end if;

  select * into selected_season
  from public.league_seasons
  where id = p_season_id;

  if selected_season.id is null then
    raise exception 'Selected season was not found.';
  end if;

  snapshot_value := public.build_season_recovery_snapshot(selected_season.id);
  row_counts_value := public.season_recovery_row_counts(snapshot_value);
  select value into schema_version_value
  from public.app_metadata
  where key = 'schema_version';
  schema_version_value := coalesce(schema_version_value, 'unknown');
  checksum_value := encode(
    extensions.digest(convert_to(snapshot_value::text, 'UTF8'), 'sha256'),
    'hex'
  );

  insert into public.season_restore_points (
    season_id,
    season_year,
    label,
    source,
    schema_version,
    row_counts,
    snapshot,
    checksum,
    created_by
  )
  values (
    selected_season.id,
    selected_season.season_year,
    trim(p_label),
    p_source,
    schema_version_value,
    row_counts_value,
    snapshot_value,
    checksum_value,
    auth.uid()
  )
  returning * into inserted_point;

  perform public.write_admin_audit_event(
    'create_season_restore_point',
    'league_season',
    selected_season.id::text,
    format('Created %s recovery point: %s.', p_source, trim(p_label)),
    null,
    jsonb_build_object(
      'restore_point_id', inserted_point.id,
      'checksum', checksum_value,
      'row_counts', row_counts_value
    )
  );

  return jsonb_build_object(
    'id', inserted_point.id,
    'seasonId', inserted_point.season_id,
    'seasonYear', inserted_point.season_year,
    'label', inserted_point.label,
    'source', inserted_point.source,
    'schemaVersion', inserted_point.schema_version,
    'formatVersion', inserted_point.format_version,
    'rowCounts', inserted_point.row_counts,
    'checksum', inserted_point.checksum,
    'createdAt', inserted_point.created_at
  );
end;
$$;

revoke all on function public.create_season_restore_point(bigint, text, text)
from public, anon;
grant execute on function public.create_season_restore_point(bigint, text, text)
to authenticated, service_role;

create or replace function public.create_restore_point_after_result_publication()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.results_status = 'published'
    and (
      old.results_status is distinct from new.results_status
      or old.results_published_at is distinct from new.results_published_at
    ) then
    perform public.create_season_restore_point(
      new.season_id,
      format('After R%s results: %s', new.round_number, new.race_name),
      'automatic'
    );
  end if;

  return new;
end;
$$;

drop trigger if exists trg_create_restore_point_after_result_publication
on public.races;
create trigger trg_create_restore_point_after_result_publication
after update of results_status, results_published_at on public.races
for each row execute function public.create_restore_point_after_result_publication();

revoke all on function public.create_restore_point_after_result_publication()
from public, anon, authenticated;

create or replace function public.import_season_restore_point(p_document jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  checksum_value text;
  computed_checksum text;
  inserted_point public.season_restore_points%rowtype;
  local_season public.league_seasons%rowtype;
  row_counts_value jsonb;
  schema_version_value text;
  season_year_value integer;
  snapshot_value jsonb;
begin
  if not public.is_admin(auth.uid()) then
    raise exception 'Admin access required.';
  end if;

  if p_document->>'format' <> 'mound-hounds-season-backup'
    or coalesce((p_document->>'formatVersion')::integer, 0) <> 1 then
    raise exception 'This is not a supported Mound Hounds season backup.';
  end if;

  snapshot_value := p_document->'snapshot';
  checksum_value := lower(trim(coalesce(p_document->>'checksum', '')));
  if jsonb_typeof(snapshot_value) <> 'object' or length(checksum_value) <> 64 then
    raise exception 'Backup snapshot or checksum is missing.';
  end if;

  computed_checksum := encode(
    extensions.digest(convert_to(snapshot_value::text, 'UTF8'), 'sha256'),
    'hex'
  );
  if computed_checksum <> checksum_value then
    raise exception 'Backup checksum validation failed. The file may be incomplete or edited.';
  end if;

  season_year_value := (snapshot_value->'season'->>'season_year')::integer;
  select * into local_season
  from public.league_seasons
  where season_year = season_year_value;
  if local_season.id is null then
    raise exception 'Create the % league season before importing this backup.', season_year_value;
  end if;

  row_counts_value := public.season_recovery_row_counts(snapshot_value);
  schema_version_value := coalesce(p_document->>'schemaVersion', 'unknown');

  insert into public.season_restore_points (
    season_id,
    season_year,
    label,
    source,
    schema_version,
    format_version,
    row_counts,
    snapshot,
    checksum,
    created_by
  )
  values (
    local_season.id,
    season_year_value,
    left(
      coalesce(nullif(trim(p_document->>'label'), ''), 'Uploaded season backup'),
      160
    ),
    'uploaded',
    schema_version_value,
    1,
    row_counts_value,
    snapshot_value,
    checksum_value,
    auth.uid()
  )
  returning * into inserted_point;

  perform public.write_admin_audit_event(
    'import_season_restore_point',
    'league_season',
    local_season.id::text,
    format('Validated and imported a %s season backup.', season_year_value),
    null,
    jsonb_build_object(
      'restore_point_id', inserted_point.id,
      'checksum', checksum_value,
      'row_counts', row_counts_value
    )
  );

  return jsonb_build_object(
    'id', inserted_point.id,
    'seasonId', inserted_point.season_id,
    'seasonYear', inserted_point.season_year,
    'label', inserted_point.label,
    'source', inserted_point.source,
    'schemaVersion', inserted_point.schema_version,
    'formatVersion', inserted_point.format_version,
    'rowCounts', inserted_point.row_counts,
    'checksum', inserted_point.checksum,
    'createdAt', inserted_point.created_at
  );
end;
$$;

revoke all on function public.import_season_restore_point(jsonb)
from public, anon;
grant execute on function public.import_season_restore_point(jsonb)
to authenticated;

create or replace function public.jsonb_array_difference_count(
  p_left jsonb,
  p_right jsonb
)
returns integer
language sql
immutable
set search_path = public
as $$
  select count(*)::integer
  from (
    (
      select value
      from jsonb_array_elements(coalesce(p_left, '[]'::jsonb))
      except
      select value
      from jsonb_array_elements(coalesce(p_right, '[]'::jsonb))
    )
    union all
    (
      select value
      from jsonb_array_elements(coalesce(p_right, '[]'::jsonb))
      except
      select value
      from jsonb_array_elements(coalesce(p_left, '[]'::jsonb))
    )
  ) differences;
$$;

revoke all on function public.jsonb_array_difference_count(jsonb, jsonb)
from public, anon, authenticated;

create or replace function public.preview_season_restore_point(p_restore_point_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  backup_point public.season_restore_points%rowtype;
  current_snapshot jsonb;
  differences jsonb := '{}'::jsonb;
  table_key text;
  table_keys text[] := array[
    'profiles',
    'participants',
    'drivers',
    'races',
    'raceDriverGroups',
    'picks',
    'pickSubmissionVersions',
    'results'
  ];
begin
  if not public.is_admin(auth.uid()) then
    raise exception 'Admin access required.';
  end if;

  select * into backup_point
  from public.season_restore_points
  where id = p_restore_point_id;
  if backup_point.id is null then
    raise exception 'Selected restore point was not found.';
  end if;

  current_snapshot := public.build_season_recovery_snapshot(backup_point.season_id);
  foreach table_key in array table_keys loop
    differences := differences || jsonb_build_object(
      table_key,
      jsonb_build_object(
        'backupCount',
        jsonb_array_length(coalesce(backup_point.snapshot->table_key, '[]'::jsonb)),
        'currentCount',
        jsonb_array_length(coalesce(current_snapshot->table_key, '[]'::jsonb)),
        'differentRows',
        public.jsonb_array_difference_count(
          backup_point.snapshot->table_key,
          current_snapshot->table_key
        )
      )
    );
  end loop;

  differences := differences || jsonb_build_object(
    'hallOfFame',
    jsonb_build_object(
      'backupCount',
      case when jsonb_typeof(backup_point.snapshot->'hallOfFame') = 'object' then 1 else 0 end,
      'currentCount',
      case when jsonb_typeof(current_snapshot->'hallOfFame') = 'object' then 1 else 0 end,
      'differentRows',
      case
        when backup_point.snapshot->'hallOfFame' is not distinct from current_snapshot->'hallOfFame'
          then 0
        else 1
      end
    )
  );

  return jsonb_build_object(
    'id', backup_point.id,
    'seasonId', backup_point.season_id,
    'seasonYear', backup_point.season_year,
    'label', backup_point.label,
    'source', backup_point.source,
    'schemaVersion', backup_point.schema_version,
    'formatVersion', backup_point.format_version,
    'checksum', backup_point.checksum,
    'createdAt', backup_point.created_at,
    'differences', differences
  );
end;
$$;

revoke all on function public.preview_season_restore_point(uuid)
from public, anon;
grant execute on function public.preview_season_restore_point(uuid)
to authenticated;

create or replace function public.enforce_pick_deadline()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  current_window_first_round smallint;
  previous_pick_window_key uuid;
  unpublished_race_names text;
  selected_is_archived boolean;
  selected_pick_format text;
  selected_pick_window_key uuid;
  selected_qualifying_start_at timestamptz;
  selected_season_id bigint;
  selected_start_at timestamptz;
  pick_lock_at timestamptz;
begin
  if current_setting('mound_hounds.restore_mode', true) = 'on' then
    return new;
  end if;

  select
    race.qualifying_start_at,
    race.race_date,
    race.is_archived,
    race.pick_format,
    race.season_id,
    race.pick_window_key
  into
    selected_qualifying_start_at,
    selected_start_at,
    selected_is_archived,
    selected_pick_format,
    selected_season_id,
    selected_pick_window_key
  from public.races race
  where race.id = new.race_id;

  if selected_qualifying_start_at is null or selected_start_at is null then
    raise exception 'Race not found for pick submission';
  end if;

  if selected_is_archived then
    raise exception 'Picks are disabled for archived races.';
  end if;

  if not public.is_registered_for_season(new.user_id, selected_season_id) then
    raise exception 'Register for this league season before submitting picks.';
  end if;

  if not exists (
    select 1
    from public.league_seasons season
    where season.id = selected_season_id
      and season.status = 'active'
  ) then
    raise exception 'Picks are only accepted for the active league season.';
  end if;

  select min(race.round_number)
  into current_window_first_round
  from public.races race
  where race.season_id = selected_season_id
    and race.pick_window_key = selected_pick_window_key
    and race.is_archived = false;

  select previous_race.pick_window_key
  into previous_pick_window_key
  from public.races previous_race
  where previous_race.is_archived = false
    and previous_race.season_id = selected_season_id
    and previous_race.round_number < current_window_first_round
  order by previous_race.round_number desc
  limit 1;

  if previous_pick_window_key is not null then
    select string_agg(previous_race.race_name, ', ' order by previous_race.round_number)
    into unpublished_race_names
    from public.races previous_race
    where previous_race.is_archived = false
      and previous_race.season_id = selected_season_id
      and previous_race.pick_window_key = previous_pick_window_key
      and previous_race.results_status <> 'published';
  end if;

  if unpublished_race_names is not null then
    raise exception 'Picks are unavailable until results are published for: %.', unpublished_race_names;
  end if;

  pick_lock_at := case
    when selected_pick_format = 'indy_500' then selected_start_at
    else selected_qualifying_start_at
  end;

  if timezone('utc', now()) >= pick_lock_at then
    if selected_pick_format = 'indy_500' then
      raise exception 'Picks are locked because the race has already started.';
    end if;
    raise exception 'Picks are locked because qualifying has already started.';
  end if;

  return new;
end;
$$;

drop trigger if exists trg_enforce_pick_deadline on public.picks;
create trigger trg_enforce_pick_deadline
before insert or update on public.picks
for each row execute function public.enforce_pick_deadline();

create or replace function public.restore_season_from_restore_point(
  p_restore_point_id uuid,
  p_confirmation_year integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  backup_point public.season_restore_points%rowtype;
  computed_checksum text;
  hall_snapshot jsonb;
  missing_profile_count integer;
  safety_point jsonb;
  selected_season public.league_seasons%rowtype;
begin
  if not public.is_admin(auth.uid()) then
    raise exception 'Admin access required.';
  end if;

  select * into backup_point
  from public.season_restore_points
  where id = p_restore_point_id
  for update;
  if backup_point.id is null then
    raise exception 'Selected restore point was not found.';
  end if;

  select * into selected_season
  from public.league_seasons
  where id = backup_point.season_id
  for update;
  if selected_season.id is null or selected_season.status <> 'active' then
    raise exception 'Only the active season can be restored.';
  end if;

  if p_confirmation_year is distinct from backup_point.season_year then
    raise exception 'Type the % season year exactly to confirm restoration.', backup_point.season_year;
  end if;

  computed_checksum := encode(
    extensions.digest(convert_to(backup_point.snapshot::text, 'UTF8'), 'sha256'),
    'hex'
  );
  if computed_checksum <> backup_point.checksum then
    raise exception 'Stored backup checksum validation failed. Restoration was cancelled.';
  end if;

  select count(*) into missing_profile_count
  from jsonb_to_recordset(coalesce(backup_point.snapshot->'profiles', '[]'::jsonb))
    as profile_row(id uuid)
  left join public.profiles profile on profile.id = profile_row.id
  where profile.id is null;
  if missing_profile_count > 0 then
    raise exception 'Restore cancelled because % permanent participant account(s) are missing.', missing_profile_count;
  end if;

  if exists (
    select 1
    from jsonb_to_recordset(coalesce(backup_point.snapshot->'drivers', '[]'::jsonb))
      as driver_row(id bigint, driver_name text)
    join public.drivers current_driver
      on lower(current_driver.driver_name) = lower(driver_row.driver_name)
      and current_driver.id <> driver_row.id
  ) then
    raise exception 'Restore cancelled because a driver name now belongs to a different driver record.';
  end if;

  safety_point := public.create_season_restore_point(
    selected_season.id,
    format('Safety snapshot before restoring: %s', backup_point.label),
    'pre_restore'
  );

  perform set_config('mound_hounds.restore_mode', 'on', true);

  delete from public.picks pick
  using public.races race
  where pick.race_id = race.id
    and race.season_id = selected_season.id;

  delete from public.results result_row
  using public.races race
  where result_row.race_id = race.id
    and race.season_id = selected_season.id;

  delete from public.race_driver_groups race_group
  using public.races race
  where race_group.race_id = race.id
    and race.season_id = selected_season.id;

  delete from public.races
  where season_id = selected_season.id;

  delete from public.season_participants
  where season_id = selected_season.id;

  delete from public.hall_of_fame_seasons
  where season_year = selected_season.season_year;

  insert into public.drivers (
    id,
    driver_name,
    image_url,
    championship_points,
    current_standing,
    opening_seed_standing,
    group_number,
    is_active,
    created_at,
    updated_at
  )
  select
    row_data.id,
    row_data.driver_name,
    row_data.image_url,
    row_data.championship_points,
    row_data.current_standing,
    row_data.opening_seed_standing,
    row_data.group_number,
    row_data.is_active,
    row_data.created_at,
    row_data.updated_at
  from jsonb_to_recordset(coalesce(backup_point.snapshot->'drivers', '[]'::jsonb))
    as row_data(
      id bigint,
      driver_name text,
      image_url text,
      championship_points integer,
      current_standing integer,
      opening_seed_standing integer,
      group_number smallint,
      is_active boolean,
      created_at timestamptz,
      updated_at timestamptz
    )
  on conflict (id) do update
  set
    driver_name = excluded.driver_name,
    image_url = excluded.image_url,
    championship_points = excluded.championship_points,
    current_standing = excluded.current_standing,
    opening_seed_standing = excluded.opening_seed_standing,
    group_number = excluded.group_number,
    is_active = excluded.is_active;

  insert into public.season_participants (
    season_id,
    profile_id,
    status,
    registered_at,
    decided_at,
    created_at,
    updated_at
  )
  select
    selected_season.id,
    row_data.profile_id,
    row_data.status,
    row_data.registered_at,
    row_data.decided_at,
    row_data.created_at,
    row_data.updated_at
  from jsonb_to_recordset(coalesce(backup_point.snapshot->'participants', '[]'::jsonb))
    as row_data(
      season_id bigint,
      profile_id uuid,
      status text,
      registered_at timestamptz,
      decided_at timestamptz,
      created_at timestamptz,
      updated_at timestamptz
    );

  insert into public.races (
    id,
    race_name,
    season_id,
    round_number,
    pick_format,
    pick_window_key,
    title_image_url,
    qualifying_start_at,
    race_date,
    payout,
    official_winning_average_speed,
    results_status,
    results_published_at,
    winner_profile_id,
    winner_source,
    winner_is_manual_override,
    winner_auto_eligible_at,
    winner_set_at,
    is_archived,
    archived_at,
    field_frozen_at,
    created_at,
    updated_at
  )
  select
    row_data.id,
    row_data.race_name,
    selected_season.id,
    row_data.round_number,
    row_data.pick_format,
    row_data.pick_window_key,
    row_data.title_image_url,
    row_data.qualifying_start_at,
    row_data.race_date,
    row_data.payout,
    row_data.official_winning_average_speed,
    row_data.results_status,
    row_data.results_published_at,
    row_data.winner_profile_id,
    row_data.winner_source,
    row_data.winner_is_manual_override,
    row_data.winner_auto_eligible_at,
    row_data.winner_set_at,
    row_data.is_archived,
    row_data.archived_at,
    row_data.field_frozen_at,
    row_data.created_at,
    row_data.updated_at
  from jsonb_to_recordset(coalesce(backup_point.snapshot->'races', '[]'::jsonb))
    as row_data(
      id bigint,
      race_name text,
      season_id bigint,
      round_number smallint,
      pick_format text,
      pick_window_key uuid,
      title_image_url text,
      qualifying_start_at timestamptz,
      race_date timestamptz,
      payout numeric,
      official_winning_average_speed numeric,
      results_status text,
      results_published_at timestamptz,
      winner_profile_id uuid,
      winner_source text,
      winner_is_manual_override boolean,
      winner_auto_eligible_at timestamptz,
      winner_set_at timestamptz,
      is_archived boolean,
      archived_at timestamptz,
      field_frozen_at timestamptz,
      created_at timestamptz,
      updated_at timestamptz
    );

  insert into public.race_driver_groups (
    race_id,
    driver_id,
    group_number,
    qualifying_position,
    created_at,
    updated_at
  )
  select
    row_data.race_id,
    row_data.driver_id,
    row_data.group_number,
    row_data.qualifying_position,
    row_data.created_at,
    row_data.updated_at
  from jsonb_to_recordset(coalesce(backup_point.snapshot->'raceDriverGroups', '[]'::jsonb))
    as row_data(
      race_id bigint,
      driver_id bigint,
      group_number smallint,
      qualifying_position integer,
      created_at timestamptz,
      updated_at timestamptz
    );

  insert into public.results (
    id,
    race_id,
    driver_id,
    points,
    created_at,
    updated_at
  )
  select
    row_data.id,
    row_data.race_id,
    row_data.driver_id,
    row_data.points,
    row_data.created_at,
    row_data.updated_at
  from jsonb_to_recordset(coalesce(backup_point.snapshot->'results', '[]'::jsonb))
    as row_data(
      id bigint,
      race_id bigint,
      driver_id bigint,
      points integer,
      created_at timestamptz,
      updated_at timestamptz
    );

  insert into public.picks (
    id,
    user_id,
    race_id,
    average_speed,
    driver_group1_id,
    driver_group2_id,
    driver_group3_id,
    driver_group4_id,
    driver_group5_id,
    driver_group6_id,
    driver_group7_id,
    driver_group8_id,
    created_at,
    updated_at
  )
  select
    row_data.id,
    row_data.user_id,
    row_data.race_id,
    row_data.average_speed,
    row_data.driver_group1_id,
    row_data.driver_group2_id,
    row_data.driver_group3_id,
    row_data.driver_group4_id,
    row_data.driver_group5_id,
    row_data.driver_group6_id,
    row_data.driver_group7_id,
    row_data.driver_group8_id,
    row_data.created_at,
    row_data.updated_at
  from jsonb_to_recordset(coalesce(backup_point.snapshot->'picks', '[]'::jsonb))
    as row_data(
      id bigint,
      user_id uuid,
      race_id bigint,
      average_speed numeric,
      driver_group1_id bigint,
      driver_group2_id bigint,
      driver_group3_id bigint,
      driver_group4_id bigint,
      driver_group5_id bigint,
      driver_group6_id bigint,
      driver_group7_id bigint,
      driver_group8_id bigint,
      created_at timestamptz,
      updated_at timestamptz
    );

  insert into public.pick_submission_versions (
    id,
    pick_id,
    user_id,
    race_id,
    submission_version,
    average_speed,
    driver_group1_id,
    driver_group2_id,
    driver_group3_id,
    driver_group4_id,
    driver_group5_id,
    driver_group6_id,
    driver_group7_id,
    driver_group8_id,
    submitted_at
  )
  select
    row_data.id,
    row_data.pick_id,
    row_data.user_id,
    row_data.race_id,
    row_data.submission_version,
    row_data.average_speed,
    row_data.driver_group1_id,
    row_data.driver_group2_id,
    row_data.driver_group3_id,
    row_data.driver_group4_id,
    row_data.driver_group5_id,
    row_data.driver_group6_id,
    row_data.driver_group7_id,
    row_data.driver_group8_id,
    row_data.submitted_at
  from jsonb_to_recordset(
    coalesce(backup_point.snapshot->'pickSubmissionVersions', '[]'::jsonb)
  )
    as row_data(
      id bigint,
      pick_id bigint,
      user_id uuid,
      race_id bigint,
      submission_version integer,
      average_speed numeric,
      driver_group1_id bigint,
      driver_group2_id bigint,
      driver_group3_id bigint,
      driver_group4_id bigint,
      driver_group5_id bigint,
      driver_group6_id bigint,
      driver_group7_id bigint,
      driver_group8_id bigint,
      submitted_at timestamptz
    );

  hall_snapshot := backup_point.snapshot->'hallOfFame';
  if jsonb_typeof(hall_snapshot) = 'object' then
    insert into public.hall_of_fame_seasons (
      id,
      season_year,
      champion_team_name,
      champion_total_points,
      participant_count,
      race_count,
      finalized_by,
      finalized_at,
      created_at,
      updated_at
    )
    select
      row_data.id,
      row_data.season_year,
      row_data.champion_team_name,
      row_data.champion_total_points,
      row_data.participant_count,
      row_data.race_count,
      row_data.finalized_by,
      row_data.finalized_at,
      row_data.created_at,
      row_data.updated_at
    from jsonb_to_record(hall_snapshot->'season')
      as row_data(
        id bigint,
        season_year integer,
        champion_team_name text,
        champion_total_points integer,
        participant_count integer,
        race_count integer,
        finalized_by uuid,
        finalized_at timestamptz,
        created_at timestamptz,
        updated_at timestamptz
      );

    insert into public.hall_of_fame_entries (
      id,
      season_id,
      final_rank,
      team_name,
      total_points,
      race_breakdown,
      created_at
    )
    select
      row_data.id,
      row_data.season_id,
      row_data.final_rank,
      row_data.team_name,
      row_data.total_points,
      row_data.race_breakdown,
      row_data.created_at
    from jsonb_to_recordset(coalesce(hall_snapshot->'entries', '[]'::jsonb))
      as row_data(
        id bigint,
        season_id bigint,
        final_rank integer,
        team_name text,
        total_points integer,
        race_breakdown jsonb,
        created_at timestamptz
      );
  end if;

  perform setval(
    pg_get_serial_sequence('public.drivers', 'id'),
    greatest(coalesce((select max(id) from public.drivers), 1), 1),
    true
  );
  perform setval(
    pg_get_serial_sequence('public.races', 'id'),
    greatest(coalesce((select max(id) from public.races), 1), 1),
    true
  );
  perform setval(
    pg_get_serial_sequence('public.results', 'id'),
    greatest(coalesce((select max(id) from public.results), 1), 1),
    true
  );
  perform setval(
    pg_get_serial_sequence('public.picks', 'id'),
    greatest(coalesce((select max(id) from public.picks), 1), 1),
    true
  );
  perform setval(
    pg_get_serial_sequence('public.pick_submission_versions', 'id'),
    greatest(coalesce((select max(id) from public.pick_submission_versions), 1), 1),
    true
  );
  perform setval(
    pg_get_serial_sequence('public.hall_of_fame_seasons', 'id'),
    greatest(coalesce((select max(id) from public.hall_of_fame_seasons), 1), 1),
    true
  );
  perform setval(
    pg_get_serial_sequence('public.hall_of_fame_entries', 'id'),
    greatest(coalesce((select max(id) from public.hall_of_fame_entries), 1), 1),
    true
  );

  perform public.refresh_driver_standings_from_published_results();
  perform set_config('mound_hounds.restore_mode', 'off', true);

  perform public.write_admin_audit_event(
    'restore_season',
    'league_season',
    selected_season.id::text,
    format('Restored %s from recovery point %s.', selected_season.season_year, backup_point.label),
    jsonb_build_object('safety_restore_point_id', safety_point->>'id'),
    jsonb_build_object(
      'restored_restore_point_id', backup_point.id,
      'row_counts', backup_point.row_counts
    )
  );

  return jsonb_build_object(
    'restoredPointId', backup_point.id,
    'safetyPointId', safety_point->>'id',
    'seasonId', selected_season.id,
    'seasonYear', selected_season.season_year,
    'rowCounts', backup_point.row_counts,
    'restoredAt', timezone('utc', now())
  );
end;
$$;

revoke all on function public.restore_season_from_restore_point(uuid, integer)
from public, anon;
grant execute on function public.restore_season_from_restore_point(uuid, integer)
to authenticated;

alter table public.season_restore_points enable row level security;

grant select on table public.season_restore_points to authenticated;

drop policy if exists season_restore_points_admin_read
on public.season_restore_points;
create policy season_restore_points_admin_read
on public.season_restore_points
for select
to authenticated
using (public.is_admin(auth.uid()));

create or replace function public.get_app_health_contract()
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  missing_items text[] := '{}';
begin
  if not public.is_admin(auth.uid()) then
    raise exception 'Admin access required.';
  end if;

  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'races'
      and column_name = 'field_frozen_at'
  ) then
    missing_items := array_append(missing_items, 'races.field_frozen_at');
  end if;

  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'races'
      and column_name = 'pick_window_key'
  ) then
    missing_items := array_append(missing_items, 'races.pick_window_key');
  end if;

  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'league_seasons'
      and column_name = 'roster_configured_at'
  ) then
    missing_items := array_append(missing_items, 'league_seasons.roster_configured_at');
  end if;

  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'feedback_items'
      and column_name = 'status'
  ) then
    missing_items := array_append(missing_items, 'feedback_items.status');
  end if;

  if to_regclass('public.season_registration_secrets') is null then
    missing_items := array_append(missing_items, 'season_registration_secrets');
  end if;
  if to_regclass('public.admin_audit_events') is null then
    missing_items := array_append(missing_items, 'admin_audit_events');
  end if;
  if to_regclass('public.job_runs') is null then
    missing_items := array_append(missing_items, 'job_runs');
  end if;
  if to_regclass('public.pick_reminders') is null then
    missing_items := array_append(missing_items, 'pick_reminders');
  end if;
  if to_regclass('public.pick_submission_versions') is null then
    missing_items := array_append(missing_items, 'pick_submission_versions');
  end if;
  if to_regclass('public.season_restore_points') is null then
    missing_items := array_append(missing_items, 'season_restore_points');
  end if;

  if to_regprocedure('public.admin_update_participant(uuid,text,text,boolean,boolean,boolean)') is null then
    missing_items := array_append(missing_items, 'admin_update_participant');
  end if;
  if to_regprocedure('public.sync_opening_driver_roster(bigint,jsonb)') is null then
    missing_items := array_append(missing_items, 'sync_opening_driver_roster');
  end if;
  if to_regprocedure('public.replace_indy_500_qualifying_order(bigint,jsonb)') is null then
    missing_items := array_append(missing_items, 'replace_indy_500_qualifying_order');
  end if;
  if to_regprocedure('public.ensure_race_pick_field_snapshot(bigint)') is null then
    missing_items := array_append(missing_items, 'ensure_race_pick_field_snapshot');
  end if;
  if to_regprocedure('public.validate_shared_pick_window()') is null then
    missing_items := array_append(missing_items, 'validate_shared_pick_window');
  end if;
  if to_regprocedure('public.claim_pick_reminder_delivery(bigint,uuid,text,text,text)') is null then
    missing_items := array_append(missing_items, 'claim_pick_reminder_delivery');
  end if;
  if to_regprocedure('public.protect_race_history_from_delete()') is null then
    missing_items := array_append(missing_items, 'protect_race_history_from_delete');
  end if;
  if to_regprocedure('public.protect_driver_history_from_delete()') is null then
    missing_items := array_append(missing_items, 'protect_driver_history_from_delete');
  end if;
  if to_regprocedure('public.save_weekly_pick(bigint,numeric,bigint[])') is null then
    missing_items := array_append(missing_items, 'save_weekly_pick');
  end if;
  if to_regprocedure('public.create_season_restore_point(bigint,text,text)') is null then
    missing_items := array_append(missing_items, 'create_season_restore_point');
  end if;
  if to_regprocedure('public.restore_season_from_restore_point(uuid,integer)') is null then
    missing_items := array_append(missing_items, 'restore_season_from_restore_point');
  end if;

  return jsonb_build_object(
    'healthy', cardinality(missing_items) = 0,
    'missing', to_jsonb(missing_items),
    'version', '20260730_atomic_picks_recovery_v1'
  );
end;
$$;

revoke all on function public.get_app_health_contract() from public, anon;
grant execute on function public.get_app_health_contract() to authenticated;

insert into public.app_metadata (key, value)
values ('schema_version', '20260730_atomic_picks_recovery_v1')
on conflict (key) do update
set value = excluded.value, updated_at = timezone('utc', now());

commit;
