-- Persist final season standings independently from active drivers, picks, and profiles.

create table if not exists public.hall_of_fame_seasons (
  id bigint generated by default as identity primary key,
  season_year integer not null unique check (season_year between 2000 and 2100),
  champion_team_name text not null check (length(trim(champion_team_name)) > 0),
  champion_total_points integer not null check (champion_total_points >= 0),
  participant_count integer not null check (participant_count > 0),
  race_count integer not null check (race_count > 0),
  finalized_by uuid references public.profiles(id) on delete set null,
  finalized_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.hall_of_fame_entries (
  id bigint generated by default as identity primary key,
  season_id bigint not null references public.hall_of_fame_seasons(id) on delete cascade,
  final_rank integer not null check (final_rank > 0),
  team_name text not null check (length(trim(team_name)) > 0),
  total_points integer not null check (total_points >= 0),
  race_breakdown jsonb not null default '[]'::jsonb check (jsonb_typeof(race_breakdown) = 'array'),
  created_at timestamptz not null default timezone('utc', now()),
  unique (season_id, team_name)
);

create index if not exists idx_hall_of_fame_seasons_year
on public.hall_of_fame_seasons(season_year desc);

create index if not exists idx_hall_of_fame_entries_season_rank
on public.hall_of_fame_entries(season_id, final_rank, team_name);

drop trigger if exists trg_hall_of_fame_seasons_updated_at on public.hall_of_fame_seasons;
create trigger trg_hall_of_fame_seasons_updated_at
before update on public.hall_of_fame_seasons
for each row execute function public.set_updated_at();

alter table public.hall_of_fame_seasons enable row level security;
alter table public.hall_of_fame_entries enable row level security;

grant select on table public.hall_of_fame_seasons to authenticated;
grant select on table public.hall_of_fame_entries to authenticated;

drop policy if exists hall_of_fame_seasons_read_authenticated on public.hall_of_fame_seasons;
create policy hall_of_fame_seasons_read_authenticated
on public.hall_of_fame_seasons
for select
to authenticated
using (true);

drop policy if exists hall_of_fame_entries_read_authenticated on public.hall_of_fame_entries;
create policy hall_of_fame_entries_read_authenticated
on public.hall_of_fame_entries
for select
to authenticated
using (true);

revoke insert, update, delete on table public.hall_of_fame_seasons from anon, authenticated;
revoke insert, update, delete on table public.hall_of_fame_entries from anon, authenticated;

create or replace function public.finalize_hall_of_fame_season(
  p_season_year integer,
  p_race_count integer,
  p_entries jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  archived_season_id bigint;
  champion_points integer;
  champion_team text;
  entry_count integer;
begin
  if not public.is_admin(auth.uid()) then
    raise exception 'Only an admin can finalize a Hall of Fame season.';
  end if;

  if p_season_year < 2000 or p_season_year > 2100 then
    raise exception 'Season year is invalid.';
  end if;

  if p_race_count is null or p_race_count <= 0 then
    raise exception 'At least one completed race is required.';
  end if;

  if p_entries is null or jsonb_typeof(p_entries) <> 'array' or jsonb_array_length(p_entries) = 0 then
    raise exception 'Final standings are required.';
  end if;

  select count(*)::integer
    into entry_count
  from jsonb_to_recordset(p_entries) as entry(
    final_rank integer,
    team_name text,
    total_points integer,
    race_breakdown jsonb
  )
  where entry.final_rank > 0
    and length(trim(entry.team_name)) > 0
    and entry.total_points >= 0
    and jsonb_typeof(coalesce(entry.race_breakdown, '[]'::jsonb)) = 'array';

  if entry_count <> jsonb_array_length(p_entries) then
    raise exception 'One or more final standings entries are invalid.';
  end if;

  if (
    select count(distinct lower(trim(entry.team_name)))
    from jsonb_to_recordset(p_entries) as entry(team_name text)
  ) <> entry_count then
    raise exception 'Final standings contain duplicate team names.';
  end if;

  select entry.team_name, entry.total_points
    into champion_team, champion_points
  from jsonb_to_recordset(p_entries) as entry(
    final_rank integer,
    team_name text,
    total_points integer
  )
  order by entry.final_rank asc, entry.total_points desc, entry.team_name asc
  limit 1;

  insert into public.hall_of_fame_seasons (
    season_year,
    champion_team_name,
    champion_total_points,
    participant_count,
    race_count,
    finalized_by,
    finalized_at
  )
  values (
    p_season_year,
    champion_team,
    champion_points,
    entry_count,
    p_race_count,
    auth.uid(),
    timezone('utc', now())
  )
  on conflict (season_year) do update
  set champion_team_name = excluded.champion_team_name,
      champion_total_points = excluded.champion_total_points,
      participant_count = excluded.participant_count,
      race_count = excluded.race_count,
      finalized_by = excluded.finalized_by,
      finalized_at = excluded.finalized_at
  returning id into archived_season_id;

  delete from public.hall_of_fame_entries
  where season_id = archived_season_id;

  insert into public.hall_of_fame_entries (
    season_id,
    final_rank,
    team_name,
    total_points,
    race_breakdown
  )
  select
    archived_season_id,
    entry.final_rank,
    trim(entry.team_name),
    entry.total_points,
    coalesce(entry.race_breakdown, '[]'::jsonb)
  from jsonb_to_recordset(p_entries) as entry(
    final_rank integer,
    team_name text,
    total_points integer,
    race_breakdown jsonb
  );

  return archived_season_id;
end;
$$;

revoke all on function public.finalize_hall_of_fame_season(integer, integer, jsonb)
from public, anon;
grant execute on function public.finalize_hall_of_fame_season(integer, integer, jsonb)
to authenticated;
