-- Add a bounded, admin-only application error inbox.

begin;

create table if not exists public.app_error_events (
  id bigint generated by default as identity primary key,
  correlation_id uuid not null unique,
  dedupe_key text unique,
  error_code text not null check (error_code ~ '^[a-z0-9][a-z0-9_.-]{2,79}$'),
  subsystem text not null check (subsystem ~ '^[a-z0-9][a-z0-9_.-]{1,39}$'),
  severity text not null default 'error' check (severity in ('warning', 'error', 'critical')),
  route text not null check (length(route) between 1 and 240),
  technical_summary text not null check (length(technical_summary) between 1 and 500),
  safe_context jsonb not null default '{}'::jsonb
    check (jsonb_typeof(safe_context) = 'object' and octet_length(safe_context::text) <= 4000),
  actor_profile_id uuid references public.profiles(id) on delete set null,
  status text not null default 'open' check (status in ('open', 'resolved')),
  occurrence_count integer not null default 1 check (occurrence_count between 1 and 1000000),
  first_seen_at timestamptz not null default timezone('utc', now()),
  last_seen_at timestamptz not null default timezone('utc', now()),
  resolved_at timestamptz,
  resolved_by uuid references public.profiles(id) on delete set null,
  check (
    (status = 'open' and resolved_at is null)
    or (status = 'resolved' and resolved_at is not null)
  )
);

create index if not exists idx_app_error_events_status_last_seen
on public.app_error_events(status, last_seen_at desc);

create index if not exists idx_app_error_events_subsystem_last_seen
on public.app_error_events(subsystem, last_seen_at desc);

alter table public.app_error_events enable row level security;

grant select on table public.app_error_events to authenticated;
revoke insert, update, delete on table public.app_error_events from public, anon, authenticated;

drop policy if exists app_error_events_admin_read on public.app_error_events;
create policy app_error_events_admin_read
on public.app_error_events
for select
to authenticated
using (public.is_admin(auth.uid()));

create or replace function public.prune_app_error_events()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  deleted_count integer := 0;
  step_count integer := 0;
begin
  if coalesce(auth.role(), '') <> 'service_role' and not public.is_admin(auth.uid()) then
    raise exception 'Admin access required.';
  end if;

  delete from public.app_error_events
  where status = 'resolved'
    and last_seen_at < timezone('utc', now()) - interval '30 days';
  get diagnostics step_count = row_count;
  deleted_count := deleted_count + step_count;

  with ranked as (
    select
      id,
      row_number() over (order by last_seen_at desc, id desc) as retention_rank
    from public.app_error_events
  )
  delete from public.app_error_events event
  using ranked
  where event.id = ranked.id
    and ranked.retention_rank > 500;
  get diagnostics step_count = row_count;

  return deleted_count + step_count;
end;
$$;

revoke all on function public.prune_app_error_events() from public, anon;
grant execute on function public.prune_app_error_events() to authenticated, service_role;

create or replace function public.record_app_error_event(
  p_correlation_id uuid,
  p_error_code text,
  p_subsystem text,
  p_severity text,
  p_route text,
  p_technical_summary text,
  p_safe_context jsonb default '{}'::jsonb,
  p_actor_profile_id uuid default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  event_row public.app_error_events%rowtype;
  normalized_code text := lower(trim(coalesce(p_error_code, '')));
  normalized_route text := left(coalesce(nullif(trim(p_route), ''), '/unknown'), 240);
  normalized_subsystem text := lower(trim(coalesce(p_subsystem, '')));
  normalized_summary text := left(trim(coalesce(p_technical_summary, '')), 500);
  next_dedupe_key text;
begin
  if coalesce(auth.role(), '') <> 'service_role' then
    raise exception 'Service role required.';
  end if;

  if p_correlation_id is null then
    raise exception 'Correlation id is required.';
  end if;
  if normalized_code !~ '^[a-z0-9][a-z0-9_.-]{2,79}$' then
    raise exception 'Invalid application error code.';
  end if;
  if normalized_subsystem !~ '^[a-z0-9][a-z0-9_.-]{1,39}$' then
    raise exception 'Invalid application error subsystem.';
  end if;
  if p_severity not in ('warning', 'error', 'critical') then
    raise exception 'Invalid application error severity.';
  end if;
  if normalized_summary = '' then
    raise exception 'Application error summary is required.';
  end if;
  if p_safe_context is null
    or jsonb_typeof(p_safe_context) <> 'object'
    or octet_length(p_safe_context::text) > 4000 then
    raise exception 'Application error context is invalid.';
  end if;
  if exists (
    select 1
    from jsonb_object_keys(p_safe_context) as context_key(key)
    where context_key.key not in (
      'digest',
      'entityId',
      'entityType',
      'httpStatus',
      'operation',
      'raceId',
      'seasonId'
    )
  ) then
    raise exception 'Application error context contains an unsupported key.';
  end if;

  next_dedupe_key := md5(
    normalized_subsystem || '|' || normalized_code || '|' || normalized_route || '|' || normalized_summary
  );

  insert into public.app_error_events (
    correlation_id,
    dedupe_key,
    error_code,
    subsystem,
    severity,
    route,
    technical_summary,
    safe_context,
    actor_profile_id
  )
  values (
    p_correlation_id,
    next_dedupe_key,
    normalized_code,
    normalized_subsystem,
    p_severity,
    normalized_route,
    normalized_summary,
    p_safe_context,
    p_actor_profile_id
  )
  on conflict (dedupe_key) do update
  set
    correlation_id = excluded.correlation_id,
    severity = case
      when app_error_events.severity = 'critical' or excluded.severity = 'critical' then 'critical'
      when app_error_events.severity = 'error' or excluded.severity = 'error' then 'error'
      else 'warning'
    end,
    safe_context = excluded.safe_context,
    actor_profile_id = coalesce(excluded.actor_profile_id, app_error_events.actor_profile_id),
    occurrence_count = least(app_error_events.occurrence_count + 1, 1000000),
    last_seen_at = timezone('utc', now())
  returning * into event_row;

  perform public.prune_app_error_events();

  return jsonb_build_object(
    'id', event_row.id,
    'correlationId', event_row.correlation_id,
    'occurrenceCount', event_row.occurrence_count
  );
end;
$$;

revoke all on function public.record_app_error_event(uuid,text,text,text,text,text,jsonb,uuid)
from public, anon, authenticated;
grant execute on function public.record_app_error_event(uuid,text,text,text,text,text,jsonb,uuid)
to service_role;

create or replace function public.resolve_app_error_event(p_event_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin(auth.uid()) then
    raise exception 'Admin access required.';
  end if;

  update public.app_error_events
  set
    status = 'resolved',
    dedupe_key = null,
    resolved_at = timezone('utc', now()),
    resolved_by = auth.uid()
  where id = p_event_id
    and status = 'open';

  if not found then
    raise exception 'Open application error was not found.';
  end if;
end;
$$;

revoke all on function public.resolve_app_error_event(bigint) from public, anon;
grant execute on function public.resolve_app_error_event(bigint) to authenticated;

commit;
