create table if not exists public.pick_reminders (
  id bigint generated by default as identity primary key,
  race_id bigint not null references public.races(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  reminder_type text not null check (reminder_type in ('4d', '2d', '2h')),
  channel text not null check (channel in ('email', 'sms')),
  recipient text not null,
  delivery_status text not null default 'pending' check (delivery_status in ('pending', 'sent')),
  delivery_id text,
  sent_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (race_id, user_id, reminder_type, channel)
);

create index if not exists idx_pick_reminders_race
on public.pick_reminders(race_id, reminder_type, channel);

create index if not exists idx_pick_reminders_user
on public.pick_reminders(user_id, created_at desc);

drop trigger if exists trg_pick_reminders_updated_at on public.pick_reminders;
create trigger trg_pick_reminders_updated_at
before update on public.pick_reminders
for each row execute function public.set_updated_at();

alter table public.pick_reminders enable row level security;

drop policy if exists pick_reminders_admin_read on public.pick_reminders;
create policy pick_reminders_admin_read
on public.pick_reminders
for select
to authenticated
using (public.is_admin(auth.uid()));
