-- Add explicit league seasons, race rounds, participant activity, and season-aware driver points.

begin;

create table if not exists public.league_seasons (
  id bigint generated by default as identity primary key,
  season_year integer not null unique check (season_year between 2000 and 2100),
  display_name text not null check (length(trim(display_name)) > 0),
  status text not null default 'upcoming' check (status in ('upcoming', 'active', 'completed')),
  activated_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists idx_league_seasons_single_active
on public.league_seasons(status)
where status = 'active';

create index if not exists idx_league_seasons_year
on public.league_seasons(season_year desc);

drop trigger if exists trg_league_seasons_updated_at on public.league_seasons;
create trigger trg_league_seasons_updated_at
before update on public.league_seasons
for each row execute function public.set_updated_at();

with race_years as (
  select distinct
    extract(year from race_date at time zone 'America/Indiana/Indianapolis')::integer as season_year
  from public.races
),
current_league_year as (
  select extract(year from timezone('America/Indiana/Indianapolis', now()))::integer as season_year
)
insert into public.league_seasons (season_year, display_name, status, activated_at, completed_at)
select
  race_years.season_year,
  race_years.season_year::text,
  case
    when race_years.season_year = current_league_year.season_year then 'active'
    when race_years.season_year < current_league_year.season_year then 'completed'
    else 'upcoming'
  end,
  case when race_years.season_year = current_league_year.season_year then timezone('utc', now()) end,
  case when race_years.season_year < current_league_year.season_year then timezone('utc', now()) end
from race_years
cross join current_league_year
on conflict (season_year) do nothing;

alter table public.races
add column if not exists season_id bigint references public.league_seasons(id) on delete restrict;

alter table public.races
add column if not exists round_number smallint;

update public.races race
set season_id = season.id
from public.league_seasons season
where race.season_id is null
  and season.season_year =
    extract(year from race.race_date at time zone 'America/Indiana/Indianapolis')::integer;

update public.races
set round_number = substring(race_name from '(?i)^\s*Race\s+([0-9]+)\s*-\s*')::smallint
where round_number is null
  and race_name ~* '^\s*Race\s+[0-9]+\s*-\s*';

with existing_rounds as (
  select season_id, coalesce(max(round_number), 0) as maximum_round
  from public.races
  group by season_id
),
unnumbered as (
  select
    race.id,
    existing_rounds.maximum_round + row_number() over (
      partition by race.season_id
      order by race.race_date asc, race.id asc
    ) as inferred_round
  from public.races race
  join existing_rounds on existing_rounds.season_id = race.season_id
  where race.round_number is null
)
update public.races race
set round_number = unnumbered.inferred_round::smallint
from unnumbered
where race.id = unnumbered.id;

update public.races
set race_name = trim(regexp_replace(race_name, '^\s*Race\s+[0-9]+\s*-\s*', '', 'i'))
where race_name ~* '^\s*Race\s+[0-9]+\s*-\s*';

alter table public.races
alter column season_id set not null;

alter table public.races
alter column round_number set not null;

alter table public.races
drop constraint if exists races_round_number_check;

alter table public.races
add constraint races_round_number_check check (round_number between 1 and 99);

alter table public.races
drop constraint if exists races_season_round_unique;

alter table public.races
add constraint races_season_round_unique unique (season_id, round_number);

create index if not exists idx_races_season_round
on public.races(season_id, round_number);

create index if not exists idx_races_season_status
on public.races(season_id, is_archived, results_status, round_number);

create or replace function public.assign_race_season_and_round()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.season_id is null then
    select season.id into new.season_id
    from public.league_seasons season
    where season.status = 'active';
  end if;

  if new.season_id is null then
    raise exception 'Create or activate a league season before adding races.';
  end if;

  if new.round_number is null then
    select (coalesce(max(race.round_number), 0) + 1)::smallint into new.round_number
    from public.races race
    where race.season_id = new.season_id;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_assign_race_season_and_round on public.races;
create trigger trg_assign_race_season_and_round
before insert on public.races
for each row execute function public.assign_race_season_and_round();

alter table public.profiles
add column if not exists is_active boolean not null default true;

create index if not exists idx_profiles_active_team
on public.profiles(is_active, team_name);

create or replace function public.protect_profile_role()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.role() = 'authenticated' and not public.is_admin(auth.uid()) then
    if tg_op = 'INSERT' and (new.role <> 'participant' or new.is_active <> true) then
      raise exception 'Only an administrator may assign protected profile fields.';
    end if;

    if tg_op = 'UPDATE' and (
      new.role is distinct from old.role
      or new.is_active is distinct from old.is_active
    ) then
      raise exception 'Only an administrator may change protected profile fields.';
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_protect_profile_role on public.profiles;
create trigger trg_protect_profile_role
before insert or update of role, is_active on public.profiles
for each row execute function public.protect_profile_role();

revoke all on function public.protect_profile_role() from public;

alter table public.drivers
add column if not exists opening_seed_standing integer;

update public.drivers
set opening_seed_standing = current_standing
where opening_seed_standing is null;

alter table public.drivers
drop constraint if exists drivers_opening_seed_standing_check;

alter table public.drivers
add constraint drivers_opening_seed_standing_check
check (opening_seed_standing is null or opening_seed_standing > 0);

alter table public.league_seasons enable row level security;

grant select, insert, update, delete on table public.league_seasons to authenticated;
grant usage, select on sequence public.league_seasons_id_seq to authenticated;

drop policy if exists league_seasons_read_authenticated on public.league_seasons;
create policy league_seasons_read_authenticated
on public.league_seasons
for select
to authenticated
using (true);

drop policy if exists league_seasons_admin_write on public.league_seasons;
create policy league_seasons_admin_write
on public.league_seasons
for all
to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

create or replace function public.activate_league_season(p_season_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  current_season public.league_seasons%rowtype;
  target_season public.league_seasons%rowtype;
begin
  if not public.is_admin(auth.uid()) then
    raise exception 'Only an admin can activate a league season.';
  end if;

  select * into target_season
  from public.league_seasons
  where id = p_season_id
  for update;

  if target_season.id is null then
    raise exception 'Selected season was not found.';
  end if;

  if target_season.status = 'completed' then
    raise exception 'A completed season cannot be reactivated.';
  end if;

  if not exists (
    select 1
    from public.races race
    where race.season_id = target_season.id
      and race.is_archived = false
  ) then
    raise exception 'Add at least one race to the target season before activating it.';
  end if;

  select * into current_season
  from public.league_seasons
  where status = 'active'
  for update;

  if current_season.id = target_season.id then
    return;
  end if;

  if current_season.id is not null and not exists (
    select 1
    from public.hall_of_fame_seasons hall
    where hall.season_year = current_season.season_year
  ) then
    raise exception 'Finalize the % Hall of Fame standings before activating a new season.', current_season.season_year;
  end if;

  if current_season.id is not null then
    update public.league_seasons
    set status = 'completed', completed_at = timezone('utc', now())
    where id = current_season.id;
  end if;

  update public.drivers
  set
    opening_seed_standing = current_standing,
    championship_points = 0
  where is_active = true;

  update public.league_seasons
  set
    status = 'active',
    activated_at = timezone('utc', now()),
    completed_at = null
  where id = target_season.id;
end;
$$;

revoke all on function public.activate_league_season(bigint) from public, anon;
grant execute on function public.activate_league_season(bigint) to authenticated;

create or replace function public.refresh_driver_standings_from_published_results()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  active_driver_count integer;
  active_season_id bigint;
  published_race_count integer;
begin
  if coalesce(auth.role(), '') <> 'service_role' and not public.is_admin(auth.uid()) then
    raise exception 'Admin access required.';
  end if;

  select id into active_season_id
  from public.league_seasons
  where status = 'active';

  if active_season_id is null then
    raise exception 'No active league season is configured.';
  end if;

  select count(*) into published_race_count
  from public.races race
  where race.season_id = active_season_id
    and race.is_archived = false
    and race.results_status = 'published';

  update public.drivers driver
  set championship_points = coalesce(points_by_driver.total_points, 0)
  from (
    select
      candidate.id as driver_id,
      coalesce(sum(result_row.points) filter (
        where race.season_id = active_season_id
          and race.is_archived = false
          and race.results_status = 'published'
      ), 0)::integer as total_points
    from public.drivers candidate
    left join public.results result_row on result_row.driver_id = candidate.id
    left join public.races race on race.id = result_row.race_id
    group by candidate.id
  ) points_by_driver
  where driver.id = points_by_driver.driver_id;

  with ranked_active as (
    select
      driver.id,
      row_number() over (
        order by
          case when published_race_count > 0 then driver.championship_points end desc,
          driver.opening_seed_standing asc nulls last,
          driver.current_standing asc,
          driver.driver_name asc
      )::integer as next_standing
    from public.drivers driver
    where driver.is_active = true
  )
  update public.drivers driver
  set
    current_standing = ranked_active.next_standing,
    group_number = case
      when ranked_active.next_standing <= 4 then 1
      when ranked_active.next_standing <= 8 then 2
      when ranked_active.next_standing <= 12 then 3
      when ranked_active.next_standing <= 16 then 4
      when ranked_active.next_standing <= 20 then 5
      else 6
    end
  from ranked_active
  where driver.id = ranked_active.id;

  select count(*) into active_driver_count
  from public.drivers driver
  where driver.is_active = true;

  with ranked_inactive as (
    select
      driver.id,
      (active_driver_count + row_number() over (
        order by driver.current_standing asc, driver.driver_name asc
      ))::integer as next_standing
    from public.drivers driver
    where driver.is_active = false
  )
  update public.drivers driver
  set
    current_standing = ranked_inactive.next_standing,
    group_number = 6
  from ranked_inactive
  where driver.id = ranked_inactive.id;
end;
$$;

revoke all on function public.refresh_driver_standings_from_published_results() from public, anon;
grant execute on function public.refresh_driver_standings_from_published_results() to authenticated, service_role;

create or replace function public.enforce_pick_deadline()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  previous_race_name text;
  previous_results_status text;
  race_is_archived boolean;
  race_pick_format text;
  race_qualifying_start_at timestamptz;
  race_round_number smallint;
  race_season_id bigint;
  race_start_at timestamptz;
  pick_lock_at timestamptz;
begin
  select
    race.qualifying_start_at,
    race.race_date,
    race.is_archived,
    race.pick_format,
    race.season_id,
    race.round_number
  into
    race_qualifying_start_at,
    race_start_at,
    race_is_archived,
    race_pick_format,
    race_season_id,
    race_round_number
  from public.races race
  where race.id = new.race_id;

  if race_qualifying_start_at is null or race_start_at is null then
    raise exception 'Race not found for pick submission';
  end if;

  if race_is_archived then
    raise exception 'Picks are disabled for archived races.';
  end if;

  if not exists (
    select 1
    from public.profiles profile
    where profile.id = new.user_id
      and profile.is_active = true
  ) then
    raise exception 'Your participant profile is inactive for the current season.';
  end if;

  if not exists (
    select 1
    from public.league_seasons season
    where season.id = race_season_id
      and season.status = 'active'
  ) then
    raise exception 'Picks are only accepted for the active league season.';
  end if;

  select previous_race.race_name, previous_race.results_status
  into previous_race_name, previous_results_status
  from public.races previous_race
  where previous_race.is_archived = false
    and previous_race.season_id = race_season_id
    and previous_race.round_number < race_round_number
  order by previous_race.round_number desc
  limit 1;

  if previous_race_name is not null and previous_results_status <> 'published' then
    raise exception 'Picks are unavailable until % results are published.', previous_race_name;
  end if;

  pick_lock_at := case
    when race_pick_format = 'indy_500' then race_start_at
    else race_qualifying_start_at
  end;

  if timezone('utc', now()) >= pick_lock_at then
    if race_pick_format = 'indy_500' then
      raise exception 'Picks are locked because the race has already started.';
    end if;
    raise exception 'Picks are locked because qualifying has already started.';
  end if;

  return new;
end;
$$;

drop trigger if exists trg_enforce_pick_deadline on public.picks;
create trigger trg_enforce_pick_deadline
before insert or update on public.picks
for each row execute function public.enforce_pick_deadline();

commit;
