-- Harden season registration, race-week field snapshots, and administrative operations.

begin;

create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

alter table public.league_seasons
add column if not exists registration_code_configured_at timestamptz,
add column if not exists roster_configured_at timestamptz,
add column if not exists rules_document_url text;

update public.league_seasons
set roster_configured_at = coalesce(roster_configured_at, timezone('utc', now()))
where status = 'active';

alter table public.races
add column if not exists field_frozen_at timestamptz;

alter table public.picks
drop constraint if exists picks_average_speed_check;

alter table public.picks
add constraint picks_average_speed_check check (average_speed > 0 and average_speed <= 300);

alter table public.races
drop constraint if exists races_official_winning_average_speed_nonnegative;

alter table public.races
drop constraint if exists races_official_winning_average_speed_check;

alter table public.races
add constraint races_official_winning_average_speed_check
check (
  official_winning_average_speed is null
  or (
    official_winning_average_speed > 0
    and official_winning_average_speed <= 300
  )
);

create table if not exists public.season_registration_secrets (
  season_id bigint primary key references public.league_seasons(id) on delete cascade,
  invite_code_hash text not null,
  updated_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.admin_audit_events (
  id bigint generated by default as identity primary key,
  actor_profile_id uuid references public.profiles(id) on delete set null,
  action text not null check (length(trim(action)) > 0),
  entity_type text not null check (length(trim(entity_type)) > 0),
  entity_id text,
  summary text not null check (length(trim(summary)) > 0),
  before_state jsonb,
  after_state jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.job_runs (
  id bigint generated by default as identity primary key,
  job_name text not null check (job_name in ('pick-reminders', 'fantasy-winner')),
  status text not null default 'running' check (status in ('running', 'succeeded', 'failed')),
  summary jsonb not null default '{}'::jsonb check (jsonb_typeof(summary) = 'object'),
  error_message text,
  started_at timestamptz not null default timezone('utc', now()),
  completed_at timestamptz,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_admin_audit_events_created
on public.admin_audit_events(created_at desc);

create index if not exists idx_admin_audit_events_entity
on public.admin_audit_events(entity_type, entity_id, created_at desc);

create index if not exists idx_job_runs_job_started
on public.job_runs(job_name, started_at desc);

drop trigger if exists trg_season_registration_secrets_updated_at
on public.season_registration_secrets;
create trigger trg_season_registration_secrets_updated_at
before update on public.season_registration_secrets
for each row execute function public.set_updated_at();

alter table public.season_registration_secrets enable row level security;
alter table public.admin_audit_events enable row level security;
alter table public.job_runs enable row level security;

revoke all on table public.season_registration_secrets from public, anon, authenticated;
grant select on table public.admin_audit_events to authenticated;
grant select on table public.job_runs to authenticated;

drop policy if exists admin_audit_events_admin_read on public.admin_audit_events;
create policy admin_audit_events_admin_read
on public.admin_audit_events
for select
to authenticated
using (public.is_admin(auth.uid()));

drop policy if exists job_runs_admin_read on public.job_runs;
create policy job_runs_admin_read
on public.job_runs
for select
to authenticated
using (public.is_admin(auth.uid()));

create or replace function public.write_admin_audit_event(
  p_action text,
  p_entity_type text,
  p_entity_id text,
  p_summary text,
  p_before_state jsonb default null,
  p_after_state jsonb default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  inserted_id bigint;
begin
  if coalesce(auth.role(), '') <> 'service_role' and not public.is_admin(auth.uid()) then
    raise exception 'Admin access required.';
  end if;

  insert into public.admin_audit_events (
    actor_profile_id,
    action,
    entity_type,
    entity_id,
    summary,
    before_state,
    after_state
  )
  values (
    auth.uid(),
    trim(p_action),
    trim(p_entity_type),
    nullif(trim(coalesce(p_entity_id, '')), ''),
    trim(p_summary),
    p_before_state,
    p_after_state
  )
  returning id into inserted_id;

  return inserted_id;
end;
$$;

revoke all on function public.write_admin_audit_event(text, text, text, text, jsonb, jsonb)
from public, anon;
grant execute on function public.write_admin_audit_event(text, text, text, text, jsonb, jsonb)
to authenticated, service_role;

create or replace function public.create_league_season(
  p_season_year integer,
  p_invite_code text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  invite_code text := trim(coalesce(p_invite_code, ''));
  inserted_season_id bigint;
begin
  if not public.is_admin(auth.uid()) then
    raise exception 'Only an admin can create a league season.';
  end if;

  if p_season_year < 2000 or p_season_year > 2100 then
    raise exception 'Enter a valid four-digit season year.';
  end if;

  if length(invite_code) < 8 or length(invite_code) > 64 then
    raise exception 'Season invite code must be between 8 and 64 characters.';
  end if;

  insert into public.league_seasons (
    season_year,
    display_name,
    status,
    registration_code_configured_at
  )
  values (
    p_season_year,
    p_season_year::text,
    'upcoming',
    timezone('utc', now())
  )
  returning id into inserted_season_id;

  insert into public.season_registration_secrets (
    season_id,
    invite_code_hash,
    updated_by
  )
  values (
    inserted_season_id,
    extensions.crypt(invite_code, extensions.gen_salt('bf', 10)),
    auth.uid()
  );

  perform public.write_admin_audit_event(
    'create',
    'league_season',
    inserted_season_id::text,
    format('Created %s season with a registration code.', p_season_year),
    null,
    jsonb_build_object('season_year', p_season_year, 'status', 'upcoming')
  );

  return inserted_season_id;
end;
$$;

revoke all on function public.create_league_season(integer, text)
from public, anon;
grant execute on function public.create_league_season(integer, text)
to authenticated;

create or replace function public.set_league_season_invite_code(
  p_season_id bigint,
  p_invite_code text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  invite_code text := trim(coalesce(p_invite_code, ''));
  selected_season public.league_seasons%rowtype;
begin
  if not public.is_admin(auth.uid()) then
    raise exception 'Only an admin can change a season invite code.';
  end if;

  if length(invite_code) < 8 or length(invite_code) > 64 then
    raise exception 'Season invite code must be between 8 and 64 characters.';
  end if;

  select * into selected_season
  from public.league_seasons
  where id = p_season_id
  for update;

  if selected_season.id is null then
    raise exception 'Selected season was not found.';
  end if;

  if selected_season.status = 'completed' then
    raise exception 'The invite code for a completed season cannot be changed.';
  end if;

  insert into public.season_registration_secrets (
    season_id,
    invite_code_hash,
    updated_by
  )
  values (
    p_season_id,
    extensions.crypt(invite_code, extensions.gen_salt('bf', 10)),
    auth.uid()
  )
  on conflict (season_id) do update
  set
    invite_code_hash = excluded.invite_code_hash,
    updated_by = excluded.updated_by;

  update public.league_seasons
  set registration_code_configured_at = timezone('utc', now())
  where id = p_season_id;

  perform public.write_admin_audit_event(
    'update_invite_code',
    'league_season',
    p_season_id::text,
    format('Updated the %s season registration code.', selected_season.season_year)
  );
end;
$$;

revoke all on function public.set_league_season_invite_code(bigint, text)
from public, anon;
grant execute on function public.set_league_season_invite_code(bigint, text)
to authenticated;

create or replace function public.require_invite_code_before_season_activation()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.status = 'active'
    and (tg_op = 'INSERT' or old.status is distinct from 'active')
    and not exists (
      select 1
      from public.season_registration_secrets secret
      where secret.season_id = new.id
    ) then
    raise exception 'Set the season invite code before activating registration.';
  end if;

  if new.status = 'active'
    and (tg_op = 'INSERT' or old.status is distinct from 'active')
    and new.roster_configured_at is null then
    raise exception 'Import the opening driver roster before activating the season.';
  end if;

  return new;
end;
$$;

drop trigger if exists trg_require_invite_code_before_season_activation
on public.league_seasons;
create trigger trg_require_invite_code_before_season_activation
before insert or update of status on public.league_seasons
for each row execute function public.require_invite_code_before_season_activation();

create or replace function public.register_profile_for_season_with_code(
  p_profile_id uuid,
  p_season_id bigint,
  p_invite_code text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  current_profile public.profiles%rowtype;
  registration_secret public.season_registration_secrets%rowtype;
  selected_season public.league_seasons%rowtype;
begin
  if coalesce(auth.role(), '') <> 'service_role' then
    raise exception 'Service role required.';
  end if;

  select * into current_profile
  from public.profiles
  where id = p_profile_id;

  if current_profile.id is null then
    raise exception 'Participant profile was not found.';
  end if;

  if current_profile.is_active = false then
    raise exception 'This account is not eligible for league participation.';
  end if;

  select * into selected_season
  from public.league_seasons
  where id = p_season_id;

  if selected_season.id is null or selected_season.status <> 'active' then
    raise exception 'Registration is only available for the active league season.';
  end if;

  if exists (
    select 1
    from public.season_participants participant
    where participant.season_id = p_season_id
      and participant.profile_id = p_profile_id
      and participant.status = 'registered'
  ) then
    return;
  end if;

  select * into registration_secret
  from public.season_registration_secrets
  where season_id = p_season_id;

  if registration_secret.season_id is null then
    raise exception 'Registration is not open yet. The league admin must configure the season invite code.';
  end if;

  if extensions.crypt(
    trim(coalesce(p_invite_code, '')),
    registration_secret.invite_code_hash
  )
    <> registration_secret.invite_code_hash then
    raise exception 'The season invite code is incorrect.';
  end if;

  insert into public.season_participants (
    season_id,
    profile_id,
    status,
    registered_at,
    decided_at
  )
  values (
    p_season_id,
    p_profile_id,
    'registered',
    timezone('utc', now()),
    timezone('utc', now())
  )
  on conflict (season_id, profile_id) do update
  set
    status = 'registered',
    registered_at = coalesce(public.season_participants.registered_at, excluded.registered_at),
    decided_at = excluded.decided_at;
end;
$$;

revoke all on function public.register_profile_for_season_with_code(uuid, bigint, text)
from public, anon, authenticated;
grant execute on function public.register_profile_for_season_with_code(uuid, bigint, text)
to service_role;

create or replace function public.validate_season_invite_code(
  p_season_id bigint,
  p_invite_code text
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.season_registration_secrets secret
    join public.league_seasons season on season.id = secret.season_id
    where secret.season_id = p_season_id
      and season.status = 'active'
      and extensions.crypt(
        trim(coalesce(p_invite_code, '')),
        secret.invite_code_hash
      )
        = secret.invite_code_hash
  );
$$;

revoke all on function public.validate_season_invite_code(bigint, text)
from public, anon, authenticated;
grant execute on function public.validate_season_invite_code(bigint, text)
to service_role;

create or replace function public.set_active_season_participation(p_register boolean)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  active_season_id bigint;
  current_profile public.profiles%rowtype;
begin
  if auth.uid() is null then
    raise exception 'Authentication required.';
  end if;

  select * into current_profile
  from public.profiles
  where id = auth.uid();

  if current_profile.id is null
    or length(trim(coalesce(current_profile.full_name, ''))) = 0
    or length(trim(coalesce(current_profile.team_name, ''))) = 0 then
    raise exception 'Complete your profile before choosing a season.';
  end if;

  if current_profile.is_active = false then
    raise exception 'This account is not eligible for league participation.';
  end if;

  select id into active_season_id
  from public.league_seasons
  where status = 'active';

  if active_season_id is null then
    raise exception 'No league season is currently open for registration.';
  end if;

  if p_register then
    if exists (
      select 1
      from public.season_participants participant
      where participant.season_id = active_season_id
        and participant.profile_id = auth.uid()
        and participant.status = 'registered'
    ) then
      return active_season_id;
    end if;

    raise exception 'Enter the season invite code to register.';
  end if;

  if exists (
    select 1
    from public.picks pick
    join public.races race on race.id = pick.race_id
    where pick.user_id = auth.uid()
      and race.season_id = active_season_id
  ) then
    raise exception 'A team with submitted picks cannot leave the active season.';
  end if;

  insert into public.season_participants (
    season_id,
    profile_id,
    status,
    registered_at,
    decided_at
  )
  values (
    active_season_id,
    auth.uid(),
    'declined',
    null,
    timezone('utc', now())
  )
  on conflict (season_id, profile_id) do update
  set
    status = 'declined',
    registered_at = null,
    decided_at = excluded.decided_at;

  return active_season_id;
end;
$$;

revoke all on function public.set_active_season_participation(boolean) from public, anon;
grant execute on function public.set_active_season_participation(boolean) to authenticated;

create or replace function public.admin_update_participant(
  p_profile_id uuid,
  p_full_name text,
  p_team_name text,
  p_account_eligible boolean,
  p_season_registered boolean,
  p_force_removal boolean default false
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  active_season_id bigint;
  before_profile jsonb;
  pick_count integer;
begin
  if not public.is_admin(auth.uid()) then
    raise exception 'Only an admin can update participant accounts.';
  end if;

  if length(trim(coalesce(p_full_name, ''))) = 0
    or length(trim(coalesce(p_team_name, ''))) = 0 then
    raise exception 'Participant full name and team name are required.';
  end if;

  select id into active_season_id
  from public.league_seasons
  where status = 'active';

  if active_season_id is null then
    raise exception 'Activate a season before changing participant registration.';
  end if;

  select to_jsonb(profile) - 'phone_number' - 'phone_carrier'
    into before_profile
  from public.profiles profile
  where profile.id = p_profile_id
  for update;

  if before_profile is null then
    raise exception 'Participant was not found.';
  end if;

  select count(distinct pick.race_id)::integer into pick_count
  from public.picks pick
  join public.races race on race.id = pick.race_id
  where pick.user_id = p_profile_id
    and race.season_id = active_season_id;

  if pick_count > 0
    and (not p_account_eligible or not p_season_registered)
    and not p_force_removal then
    raise exception 'This participant has picks in % active-season race(s). Use forced removal only when you intend to remove them from scoring.', pick_count;
  end if;

  update public.profiles
  set
    full_name = trim(p_full_name),
    team_name = trim(p_team_name),
    is_active = p_account_eligible
  where id = p_profile_id;

  insert into public.season_participants (
    season_id,
    profile_id,
    status,
    registered_at,
    decided_at
  )
  values (
    active_season_id,
    p_profile_id,
    case when p_season_registered then 'registered' else 'declined' end,
    case when p_season_registered then timezone('utc', now()) else null end,
    timezone('utc', now())
  )
  on conflict (season_id, profile_id) do update
  set
    status = excluded.status,
    registered_at = case
      when excluded.status = 'registered'
        then coalesce(public.season_participants.registered_at, excluded.registered_at)
      else null
    end,
    decided_at = excluded.decided_at;

  perform public.write_admin_audit_event(
    'update',
    'participant',
    p_profile_id::text,
    format(
      'Updated participant eligibility and %s registration.%s',
      (select season_year from public.league_seasons where id = active_season_id),
      case when p_force_removal then ' Forced removal was authorized.' else '' end
    ),
    before_profile,
    (
      select (to_jsonb(profile) - 'phone_number' - 'phone_carrier')
        || jsonb_build_object(
          'season_id', active_season_id,
          'season_registered', p_season_registered,
          'active_season_pick_count', pick_count
        )
      from public.profiles profile
      where profile.id = p_profile_id
    )
  );

  return pick_count;
end;
$$;

revoke all on function public.admin_update_participant(uuid, text, text, boolean, boolean, boolean)
from public, anon;
grant execute on function public.admin_update_participant(uuid, text, text, boolean, boolean, boolean)
to authenticated;

create or replace function public.sync_opening_driver_roster(
  p_season_id bigint,
  p_rows jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  target_season public.league_seasons%rowtype;
  created_count integer := 0;
  incoming_count integer;
  item jsonb;
  normalized_names text[];
  result_row_count integer;
  submitted_pick_count integer;
  updated_count integer := 0;
begin
  if not public.is_admin(auth.uid()) then
    raise exception 'Only an admin can import the opening driver roster.';
  end if;

  if jsonb_typeof(p_rows) <> 'array' or jsonb_array_length(p_rows) = 0 then
    raise exception 'Opening roster must contain at least one driver.';
  end if;

  select * into target_season
  from public.league_seasons
  where id = p_season_id
  for update;

  if target_season.id is null or target_season.status = 'completed' then
    raise exception 'Select an active or upcoming season for its opening roster.';
  end if;

  if target_season.status = 'upcoming' and exists (
    select 1
    from public.league_seasons current_season
    where current_season.status = 'active'
      and not exists (
        select 1
        from public.hall_of_fame_seasons hall
        where hall.season_year = current_season.season_year
      )
  ) then
    raise exception 'Finalize the current Hall of Fame standings before preparing the next driver roster.';
  end if;

  select count(*)::integer into result_row_count
  from public.results result_row
  join public.races race on race.id = result_row.race_id
  where race.season_id = target_season.id;

  select count(*)::integer into submitted_pick_count
  from public.picks pick
  join public.races race on race.id = pick.race_id
  where race.season_id = target_season.id;

  if result_row_count > 0 or submitted_pick_count > 0 then
    raise exception 'The opening roster is locked after picks or published results exist.';
  end if;

  select
    count(*)::integer,
    array_agg(lower(trim(row_data.driver_name)) order by row_data.rank)
  into incoming_count, normalized_names
  from jsonb_to_recordset(p_rows)
    as row_data(driver_id bigint, driver_name text, rank integer);

  if incoming_count <> (
    select count(distinct normalized_name)
    from unnest(normalized_names) as normalized_name
  ) then
    raise exception 'Opening roster contains duplicate driver names.';
  end if;

  if exists (
    select 1
    from jsonb_to_recordset(p_rows)
      as row_data(driver_id bigint, driver_name text, rank integer)
    where length(trim(coalesce(row_data.driver_name, ''))) = 0
      or row_data.rank is null
      or row_data.rank < 1
      or (
        row_data.driver_id is not null
        and not exists (
          select 1 from public.drivers driver where driver.id = row_data.driver_id
        )
      )
  ) then
    raise exception 'Every roster row requires a driver name and positive rank.';
  end if;

  if (
    select count(distinct row_data.rank)
    from jsonb_to_recordset(p_rows)
      as row_data(driver_id bigint, driver_name text, rank integer)
  ) <> incoming_count then
    raise exception 'Opening roster contains duplicate ranks.';
  end if;

  update public.drivers
  set is_active = false;

  for item in select value from jsonb_array_elements(p_rows)
  loop
    if nullif(item->>'driver_id', '') is not null then
      update public.drivers
      set
        driver_name = trim(item->>'driver_name'),
        championship_points = 0,
        current_standing = (item->>'rank')::integer,
        opening_seed_standing = (item->>'rank')::integer,
        group_number = case
          when (item->>'rank')::integer <= 4 then 1
          when (item->>'rank')::integer <= 8 then 2
          when (item->>'rank')::integer <= 12 then 3
          when (item->>'rank')::integer <= 16 then 4
          when (item->>'rank')::integer <= 20 then 5
          else 6
        end,
        is_active = true
      where id = (item->>'driver_id')::bigint;
      updated_count := updated_count + 1;
    elsif exists (
      select 1
      from public.drivers
      where lower(trim(driver_name)) = lower(trim(item->>'driver_name'))
    ) then
      update public.drivers
      set
        championship_points = 0,
        current_standing = (item->>'rank')::integer,
        opening_seed_standing = (item->>'rank')::integer,
        group_number = case
          when (item->>'rank')::integer <= 4 then 1
          when (item->>'rank')::integer <= 8 then 2
          when (item->>'rank')::integer <= 12 then 3
          when (item->>'rank')::integer <= 16 then 4
          when (item->>'rank')::integer <= 20 then 5
          else 6
        end,
        is_active = true
      where lower(trim(driver_name)) = lower(trim(item->>'driver_name'));
      updated_count := updated_count + 1;
    else
      insert into public.drivers (
        driver_name,
        championship_points,
        current_standing,
        opening_seed_standing,
        group_number,
        is_active
      )
      values (
        trim(item->>'driver_name'),
        0,
        (item->>'rank')::integer,
        (item->>'rank')::integer,
        case
          when (item->>'rank')::integer <= 4 then 1
          when (item->>'rank')::integer <= 8 then 2
          when (item->>'rank')::integer <= 12 then 3
          when (item->>'rank')::integer <= 16 then 4
          when (item->>'rank')::integer <= 20 then 5
          else 6
        end,
        true
      );
      created_count := created_count + 1;
    end if;
  end loop;

  with ranked_inactive as (
    select
      id,
      incoming_count + row_number() over (
        order by current_standing asc, driver_name asc
      )::integer as next_standing
    from public.drivers
    where is_active = false
  )
  update public.drivers driver
  set
    current_standing = ranked_inactive.next_standing,
    group_number = 6
  from ranked_inactive
  where driver.id = ranked_inactive.id;

  update public.league_seasons
  set roster_configured_at = timezone('utc', now())
  where id = target_season.id;

  perform public.write_admin_audit_event(
    'sync_opening_roster',
    'driver_roster',
    target_season.id::text,
    format(
      'Synchronized opening roster: %s updated, %s created, absent drivers made inactive.',
      updated_count,
      created_count
    ),
    null,
    jsonb_build_object(
      'active_driver_count', incoming_count,
      'updated_count', updated_count,
      'created_count', created_count
    )
  );

  return jsonb_build_object(
    'active_driver_count', incoming_count,
    'updated_count', updated_count,
    'created_count', created_count
  );
end;
$$;

revoke all on function public.sync_opening_driver_roster(bigint, jsonb)
from public, anon;
grant execute on function public.sync_opening_driver_roster(bigint, jsonb)
to authenticated;

create or replace function public.replace_indy_500_qualifying_order(
  p_race_id bigint,
  p_rows jsonb
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  inserted_count integer;
  selected_race public.races%rowtype;
begin
  if not public.is_admin(auth.uid()) then
    raise exception 'Only an admin can replace qualifying order.';
  end if;

  select * into selected_race
  from public.races
  where id = p_race_id
  for update;

  if selected_race.id is null then
    raise exception 'Selected race was not found.';
  end if;

  if selected_race.is_archived or selected_race.pick_format <> 'indy_500' then
    raise exception 'Select an active Indianapolis 500 race.';
  end if;

  if selected_race.field_frozen_at is not null
    or exists (select 1 from public.picks where race_id = p_race_id)
    or exists (select 1 from public.results where race_id = p_race_id) then
    raise exception 'Qualifying groups are locked because the race field, picks, or results already exist.';
  end if;

  if jsonb_typeof(p_rows) <> 'array' or jsonb_array_length(p_rows) <> 33 then
    raise exception 'Indianapolis 500 qualifying order must contain exactly 33 drivers.';
  end if;

  if exists (
    select 1
    from jsonb_to_recordset(p_rows)
      as row_data(driver_id bigint, group_number integer, qualifying_position integer)
    where row_data.driver_id is null
      or row_data.group_number not between 1 and 8
      or row_data.qualifying_position not between 1 and 33
      or row_data.group_number <> least(
        8,
        (((row_data.qualifying_position - 1) / 4) + 1)
      )
  ) then
    raise exception 'Qualifying payload contains invalid drivers, groups, or positions.';
  end if;

  if (
    select count(distinct row_data.driver_id)
    from jsonb_to_recordset(p_rows)
      as row_data(driver_id bigint, group_number integer, qualifying_position integer)
  ) <> 33 or (
    select count(distinct row_data.qualifying_position)
    from jsonb_to_recordset(p_rows)
      as row_data(driver_id bigint, group_number integer, qualifying_position integer)
  ) <> 33 then
    raise exception 'Qualifying drivers and positions must be unique.';
  end if;

  if exists (
    select 1
    from jsonb_to_recordset(p_rows)
      as row_data(driver_id bigint, group_number integer, qualifying_position integer)
    left join public.drivers driver on driver.id = row_data.driver_id
    where driver.id is null
  ) then
    raise exception 'Qualifying payload contains an unknown driver.';
  end if;

  delete from public.race_driver_groups
  where race_id = p_race_id;

  insert into public.race_driver_groups (
    race_id,
    driver_id,
    group_number,
    qualifying_position
  )
  select
    p_race_id,
    row_data.driver_id,
    row_data.group_number,
    row_data.qualifying_position
  from jsonb_to_recordset(p_rows)
    as row_data(driver_id bigint, group_number integer, qualifying_position integer);

  get diagnostics inserted_count = row_count;

  perform public.write_admin_audit_event(
    'replace_qualifying_order',
    'race',
    p_race_id::text,
    format('Imported %s Indianapolis 500 qualifying rows.', inserted_count),
    null,
    jsonb_build_object('qualifying_row_count', inserted_count)
  );

  return inserted_count;
end;
$$;

revoke all on function public.replace_indy_500_qualifying_order(bigint, jsonb)
from public, anon;
grant execute on function public.replace_indy_500_qualifying_order(bigint, jsonb)
to authenticated;

create or replace function public.ensure_race_pick_field_snapshot(p_race_id bigint)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  selected_race public.races%rowtype;
  snapshot_count integer;
begin
  select * into selected_race
  from public.races
  where id = p_race_id
  for update;

  if selected_race.id is null then
    raise exception 'Selected race was not found.';
  end if;

  if selected_race.is_archived then
    raise exception 'Archived races cannot open a pick field.';
  end if;

  if selected_race.field_frozen_at is null then
    if selected_race.pick_format = 'standard' then
      insert into public.race_driver_groups (
        race_id,
        driver_id,
        group_number,
        qualifying_position
      )
      select
        selected_race.id,
        driver.id,
        driver.group_number,
        null
      from public.drivers driver
      where driver.is_active = true
      on conflict (race_id, driver_id) do nothing;
    end if;

    select count(*)::integer into snapshot_count
    from public.race_driver_groups
    where race_id = selected_race.id;

    if selected_race.pick_format = 'indy_500' and snapshot_count <> 33 then
      raise exception 'Import the complete 33-driver qualifying order before opening Indianapolis 500 picks.';
    end if;

    if selected_race.pick_format = 'standard' and (
      snapshot_count < 6 or exists (
        select group_number
        from generate_series(1, 6) as expected(group_number)
        where not exists (
          select 1
          from public.race_driver_groups race_group
          where race_group.race_id = selected_race.id
            and race_group.group_number = expected.group_number
        )
      )
    ) then
      raise exception 'Every standard pick group must contain at least one active driver before picks can open.';
    end if;

    update public.races
    set field_frozen_at = timezone('utc', now())
    where id = selected_race.id;
  else
    select count(*)::integer into snapshot_count
    from public.race_driver_groups
    where race_id = selected_race.id;
  end if;

  return snapshot_count;
end;
$$;

revoke all on function public.ensure_race_pick_field_snapshot(bigint) from public, anon;
grant execute on function public.ensure_race_pick_field_snapshot(bigint)
to service_role;

create or replace function public.protect_frozen_race_configuration()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if old.field_frozen_at is not null
    or exists (select 1 from public.picks where race_id = old.id)
    or exists (select 1 from public.results where race_id = old.id) then
    if new.season_id is distinct from old.season_id
      or new.round_number is distinct from old.round_number
      or new.pick_format is distinct from old.pick_format then
      raise exception 'Season, round, and pick format are locked after a race field, pick, or result exists.';
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_protect_frozen_race_configuration on public.races;
create trigger trg_protect_frozen_race_configuration
before update of season_id, round_number, pick_format on public.races
for each row execute function public.protect_frozen_race_configuration();

create or replace function public.protect_race_history_from_delete()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if exists (select 1 from public.picks where race_id = old.id)
    or exists (select 1 from public.results where race_id = old.id) then
    raise exception 'A race with picks or results cannot be deleted. Archive it instead.';
  end if;

  return old;
end;
$$;

drop trigger if exists trg_protect_race_history_from_delete on public.races;
create trigger trg_protect_race_history_from_delete
before delete on public.races
for each row execute function public.protect_race_history_from_delete();

create or replace function public.protect_driver_history_from_delete()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if exists (
    select 1
    from public.picks pick
    where old.id in (
      pick.driver_group1_id,
      pick.driver_group2_id,
      pick.driver_group3_id,
      pick.driver_group4_id,
      pick.driver_group5_id,
      pick.driver_group6_id,
      pick.driver_group7_id,
      pick.driver_group8_id
    )
  ) or exists (
    select 1 from public.results where driver_id = old.id
  ) or exists (
    select 1 from public.race_driver_groups where driver_id = old.id
  ) then
    raise exception 'A driver referenced by league history cannot be deleted. Mark the driver inactive instead.';
  end if;

  return old;
end;
$$;

drop trigger if exists trg_protect_driver_history_from_delete on public.drivers;
create trigger trg_protect_driver_history_from_delete
before delete on public.drivers
for each row execute function public.protect_driver_history_from_delete();

create or replace function public.validate_pick_groups()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  selected_driver_ids bigint[];
  distinct_count integer;
  group_index integer;
  selected_driver_id bigint;
  race_pick_format text;
  expected_group_count integer;
begin
  select race.pick_format into race_pick_format
  from public.races race
  where race.id = new.race_id;

  if race_pick_format is null then
    raise exception 'Race not found for pick validation';
  end if;

  perform public.ensure_race_pick_field_snapshot(new.race_id);

  expected_group_count := case when race_pick_format = 'indy_500' then 8 else 6 end;
  selected_driver_ids := (array[
    new.driver_group1_id,
    new.driver_group2_id,
    new.driver_group3_id,
    new.driver_group4_id,
    new.driver_group5_id,
    new.driver_group6_id,
    new.driver_group7_id,
    new.driver_group8_id
  ])[1:expected_group_count];

  if race_pick_format = 'indy_500'
    and (new.driver_group7_id is null or new.driver_group8_id is null) then
    raise exception 'Indianapolis 500 picks require one driver from each of 8 groups';
  end if;

  if race_pick_format <> 'indy_500'
    and (new.driver_group7_id is not null or new.driver_group8_id is not null) then
    raise exception 'Standard race picks must contain exactly 6 drivers';
  end if;

  for group_index in 1..expected_group_count loop
    selected_driver_id := selected_driver_ids[group_index];

    if not exists (
      select 1
      from public.race_driver_groups race_group
      where race_group.race_id = new.race_id
        and race_group.driver_id = selected_driver_id
        and race_group.group_number = group_index
    ) then
      raise exception 'Invalid Group % driver for the frozen race field', group_index;
    end if;
  end loop;

  select count(distinct driver_id) into distinct_count
  from unnest(selected_driver_ids) as selected(driver_id);

  if distinct_count <> expected_group_count then
    raise exception 'Each pick must contain % distinct drivers', expected_group_count;
  end if;

  return new;
end;
$$;

create or replace function public.start_job_run(p_job_name text)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  inserted_id bigint;
begin
  if coalesce(auth.role(), '') <> 'service_role' then
    raise exception 'Service role required.';
  end if;

  insert into public.job_runs (job_name)
  values (p_job_name)
  returning id into inserted_id;

  return inserted_id;
end;
$$;

create or replace function public.finish_job_run(
  p_job_run_id bigint,
  p_status text,
  p_summary jsonb default '{}'::jsonb,
  p_error_message text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if coalesce(auth.role(), '') <> 'service_role' then
    raise exception 'Service role required.';
  end if;

  if p_status not in ('succeeded', 'failed') then
    raise exception 'Job completion status must be succeeded or failed.';
  end if;

  update public.job_runs
  set
    status = p_status,
    summary = coalesce(p_summary, '{}'::jsonb),
    error_message = nullif(left(coalesce(p_error_message, ''), 2000), ''),
    completed_at = timezone('utc', now())
  where id = p_job_run_id
    and status = 'running';
end;
$$;

revoke all on function public.start_job_run(text) from public, anon, authenticated;
revoke all on function public.finish_job_run(bigint, text, jsonb, text)
from public, anon, authenticated;
grant execute on function public.start_job_run(text) to service_role;
grant execute on function public.finish_job_run(bigint, text, jsonb, text)
to service_role;

create or replace function public.get_app_health_contract()
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  missing_items text[] := '{}';
begin
  if not public.is_admin(auth.uid()) then
    raise exception 'Admin access required.';
  end if;

  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'races'
      and column_name = 'field_frozen_at'
  ) then
    missing_items := array_append(missing_items, 'races.field_frozen_at');
  end if;

  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'league_seasons'
      and column_name = 'roster_configured_at'
  ) then
    missing_items := array_append(missing_items, 'league_seasons.roster_configured_at');
  end if;

  if to_regclass('public.season_registration_secrets') is null then
    missing_items := array_append(missing_items, 'season_registration_secrets');
  end if;

  if to_regclass('public.admin_audit_events') is null then
    missing_items := array_append(missing_items, 'admin_audit_events');
  end if;

  if to_regclass('public.job_runs') is null then
    missing_items := array_append(missing_items, 'job_runs');
  end if;

  if to_regprocedure('public.admin_update_participant(uuid,text,text,boolean,boolean,boolean)') is null then
    missing_items := array_append(missing_items, 'admin_update_participant');
  end if;

  if to_regprocedure('public.sync_opening_driver_roster(bigint,jsonb)') is null then
    missing_items := array_append(missing_items, 'sync_opening_driver_roster');
  end if;

  if to_regprocedure('public.replace_indy_500_qualifying_order(bigint,jsonb)') is null then
    missing_items := array_append(missing_items, 'replace_indy_500_qualifying_order');
  end if;

  if to_regprocedure('public.protect_race_history_from_delete()') is null then
    missing_items := array_append(missing_items, 'protect_race_history_from_delete');
  end if;

  if to_regprocedure('public.protect_driver_history_from_delete()') is null then
    missing_items := array_append(missing_items, 'protect_driver_history_from_delete');
  end if;

  return jsonb_build_object(
    'healthy', cardinality(missing_items) = 0,
    'missing', to_jsonb(missing_items),
    'version', '20260725_operations_v2'
  );
end;
$$;

revoke all on function public.get_app_health_contract() from public, anon;
grant execute on function public.get_app_health_contract() to authenticated;

insert into public.app_metadata (key, value)
values ('schema_version', '20260725_operations_v2')
on conflict (key) do update
set value = excluded.value, updated_at = timezone('utc', now());

commit;
