create table if not exists public.feedback_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  feedback_type text not null check (feedback_type in ('bug', 'improvement')),
  category text not null,
  context_page text,
  details text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_feedback_items_created_at
on public.feedback_items(created_at desc);

create index if not exists idx_feedback_items_user
on public.feedback_items(user_id);

drop trigger if exists trg_feedback_items_updated_at on public.feedback_items;
create trigger trg_feedback_items_updated_at
before update on public.feedback_items
for each row execute function public.set_updated_at();

alter table public.feedback_items enable row level security;

drop policy if exists feedback_items_select_own_or_admin on public.feedback_items;
create policy feedback_items_select_own_or_admin
on public.feedback_items
for select
to authenticated
using (user_id = auth.uid() or public.is_admin(auth.uid()));

drop policy if exists feedback_items_insert_own on public.feedback_items;
create policy feedback_items_insert_own
on public.feedback_items
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists feedback_items_update_admin on public.feedback_items;
create policy feedback_items_update_admin
on public.feedback_items
for update
to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists feedback_items_delete_admin on public.feedback_items;
create policy feedback_items_delete_admin
on public.feedback_items
for delete
to authenticated
using (public.is_admin(auth.uid()));
